### ISSUE TITLE
logs check not generating valid yaml

### ISSUE THREAD

**Issue by cscheib** [DataDog/ansible-datadog#123]
OS: Ubuntu 16.04
Ansible: 2.5.0

**datadog.yml (ansible playbook)**
```yaml
- hosts: all
  roles:
    - { role: Datadog.datadog, become: yes }  # On Ansible < 1.9, use `sudo: yes` instead of `become: yes`
  vars:
    datadog_api_key: "REDACTED"
    datadog_agent_version: "1:6.1.3-1" # for apt-based platforms, use a `6.0.0-1` format on yum-based platforms
    datadog_config:
      tags: "ddtag"
      log_level: INFO
      apm_enabled: "false" # has to be set as a string
      logs_enabled: true  # log collection is available on agent 6
    datadog_checks:
      logs:
        - type: file
          path: /var/log/alternatives.log
          service: syslog
          source: syslog
        - type: file
          path: /var/log/apt/history.log
          service: syslog
          source: syslog
        - type: file
          path: /var/log/auth.log
          service: syslog
          source: syslog
        - type: file
          path: /var/log/cloud-init.log
          service: syslog
          source: syslog
        - type: file
          path: /var/log/dpkg.log
          service: syslog
          source: syslog
        - type: file
          path: /var/log/kern.log
          service: syslog
          source: syslog
        - type: file
          path: /var/log/syslog
          service: syslog
          source: syslog
        - type: file
          path: /var/log/upstart/systemd-logind.log
          service: syslog
          source: syslog

```
generates:
**/etc/datadog-agent/conf.d/logs.yml (datadog-agent config file)**
```yaml
-   path: /var/log/alternatives.log
    service: syslog
    source: syslog
    type: file
-   path: /var/log/apt/history.log
    service: syslog
    source: syslog
    type: file
-   path: /var/log/auth.log
    service: syslog
    source: syslog
    type: file
-   path: /var/log/cloud-init.log
    service: syslog
    source: syslog
    type: file
-   path: /var/log/dpkg.log
    service: syslog
    source: syslog
    type: file
-   path: /var/log/kern.log
    service: syslog
    source: syslog
    type: file
-   path: /var/log/syslog
    service: syslog
    source: syslog
    type: file
-   path: /var/log/upstart/systemd-logind.log
    service: syslog
    source: syslog
    type: file
```
**errors: /var/log/datadog/agent.log**
```
2018-04-17 17:51:21 UTC | INFO | (start.go:156 in StartAgent) | Starting Datadog Agent v6.1.3
2018-04-17 17:51:21 UTC | INFO | (start.go:167 in StartAgent) | pid '117229' written to pid file '/opt/datadog-agent/run/agent.pid'
2018-04-17 17:51:21 UTC | INFO | (start.go:174 in StartAgent) | Hostname is: REDACTED
2018-04-17 17:51:22 UTC | INFO | (start.go:191 in StartAgent) | GUI server port -1 specified: not starting the GUI.
2018-04-17 17:51:22 UTC | INFO | (forwarder.go:235 in Start) | DefaultForwarder started (1 workers), sending to 1 endpoint(s): "https://6-1-
3-app.agent.datadoghq.com" (1 api key(s))
2018-04-17 17:51:22 UTC | ERROR | (integration_config.go:89 in buildLogSourcesFromDirectory) | While parsing config: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into map[string]interface {}
2018-04-17 17:51:22 UTC | ERROR | (start.go:228 in StartAgent) | Could not start logs-agent: could not find any valid logs configuration
```
This file is missing `logs:` from the first line.  Adding this in manually works.

**Comment by cscheib** [comment]
I managed to fix it, after I figured out how the role unfurls the yaml structure from the playbook.

The README for this role could potentially benefit from some more documentation on generic cases under the "datadog_checks" heading... or documented examples on all of the built-in checks.

```yaml
- hosts: all
  roles:
    - { role: Datadog.datadog, become: yes }  # On Ansible < 1.9, use `sudo: yes` instead of `become: yes`
  vars:
    datadog_api_key: "REDACTED"
    datadog_agent_version: "1:6.1.3-1" # for apt-based platforms, use a `6.0.0-1` format on yum-based platforms
    datadog_config:
      tags: "ddtag"
      log_level: INFO
      apm_enabled: "false" # has to be set as a string
      logs_enabled: true  # log collection is available on agent 6
    datadog_checks:
      logs:
        logs:
          - type: file
            path: /var/log/alternatives.log
            service: syslog
            source: syslog
          - type: file
            path: /var/log/apt/history.log
            service: syslog
            source: syslog
          - type: file
            path: /var/log/auth.log
            service: syslog
            source: syslog
          - type: file
            path: /var/log/cloud-init.log
            service: syslog
            source: syslog
          - type: file
            path: /var/log/dpkg.log
            service: syslog
            source: syslog
          - type: file
            path: /var/log/kern.log
            service: syslog
            source: syslog
          - type: file
            path: /var/log/syslog
            service: syslog
            source: syslog
          - type: file
            path: /var/log/upstart/systemd-logind.log
            service: syslog
            source: syslog
```
