### ISSUE TITLE
Datadog checks enabled from the example playbook in this repo create yaml file in /etc/datadog-agent/conf.d/<whatever-name>.yaml. Is that the standard behavior?

### ISSUE THREAD

**Issue by SohamChakraborty** [DataDog/ansible-datadog#131]
I am asking because my assumption is that the checks should reside in `/etc/datadog-agent/conf.d/<relevant-directory>.d/conf.yaml` file. 
For example, with this variables file, a new yaml file called process.yaml is created in `/etc/datadog-agent/conf.d` directory.

```
# cat main.yml 
---

# The following are the site wide default variables
# for datadog

datadog_enabled: yes
datadog_agent_version: 6.1.0
datadog_api_key: xxxxxxx

datadog_checks:
  process:
    init_config:
    instances:
     - name: ssh
       search_string: ['ssh', 'sshd']

```
What I thought about best practice is that maybe we should insert our checks in `/etc/datadog-agent/conf.d/process.d/conf.yaml`. Is that not so?
