### ISSUE TITLE
service datadog-agent not enabled on systemd

### ISSUE THREAD

**Issue by kcd83** [DataDog/ansible-datadog#145]
On CentOS 7 the service is not enabled with Systemd. The following is not working

```
  service:
    name: datadog-agent
    state: started
    enabled: yes
```

This is actually an ansible bug here: https://github.com/ansible/ansible/issues/39116

I'm lodging it here in case others find it or if a workaround is required (appending `.service`  to the name does it).
