### ISSUE TITLE
Config for max_traces_per_second?

### ISSUE THREAD

**Issue by wenbochang** [DataDog/ansible-datadog#163]
Sorry if I missed something obvious, but inside the static conf file, I can set:

```
apm_config:
    enabled: true
    max_traces_per_second: 100
```

Is there a similar mapping inside ansible?

```
datadog_config:
    apm_enabled: true
    ?max_traces_per_second?: 100
```

I checked https://github.com/DataDog/ansible-datadog/blob/master/tests/test_6_full.yml but couldn't find an explicit setting, maybe inside `trace.config`?

**Comment by hush-hush** [comment]
Yes, everything under `datadog_config` will endup in `datadog.yaml`.

Following this [documentation](https://docs.datadoghq.com/tracing/setup/?tab=agent630#trace-collection) `max_traces_per_second` should be set in datadog.yaml under `apm_config`.

So just do this in your ansible playbook:
```yaml
datadog_config:
    apm_config:
        enabled: true
        max_traces_per_second: 100
```

This will produce a datadog.yaml containing:
```yaml
apm_config:
    enabled: true
    max_traces_per_second: 100
```

See `datadog_config` in [Role Variables](https://github.com/DataDog/ansible-datadog#role-variables) for more.

**Comment by hush-hush** [comment]
Also depending if you're using agent v5 or v6 the key to enable APM is different.

With agent V5:
```yaml
datadog_config:
    apm_enabled: "true"
```

With agent V6:
```yaml
datadog_config:
    apm_config:
        enabled: true
```

I'll update the README to reflect that difference !
