### ISSUE TITLE
datadog_agent_version syntax issue

### ISSUE THREAD

**Issue by mdeggies** [DataDog/ansible-datadog#174]
It took awhile to figure out the correct syntax for locking the datadog agent version with `datadog_agent_version`. The actual yum package names are in the format `1:datadog-agent-6.8.0-1.x86_64`, but it looks like the authors prepend `datadog-agent:1` onto the version provided. So
`6.8.0-1.x86_64` works, but `6.8.0`, `6.8.0-1`, `1:6.8.0-1`, and the actual package name `1:datadog-agent-6.8.0-1.x86_64` fail without error. 

This should be updated in the documentation + readme.

**Comment by hush-hush** [comment]
Hi @mdeggies,

Thanks for opening this issue. We actually have a point in the README [here](https://github.com/DataDog/ansible-datadog#role-variables):

```
datadog_agent_version - The pinned version of the Agent to install (optional, but highly recommended) Examples: 1:6.0.0-1 on apt-based platforms, 6.0.0-1 on yum-based platforms
``` 

I just tried it on a centos 7.5 box and is worked.

my test playbook is:
```yaml
---
- hosts: all
  roles:
    - { role: 'Datadog.datadog'}
  vars:
    datadog_api_key: "11111111111111111111111111111111"
    datadog_agent_version: 6.6.0-1
```

Keep in mind that if you want to downgrade the agent you must set `datadog_agent_allow_downgrade` to true (see the same section in the README).

What os are you using ? Which version are you trying to install ?
