### ISSUE TITLE
to_nice_yaml outputting incorrectly formatted .yaml files

### ISSUE THREAD

**Issue by mattdlh** [DataDog/ansible-datadog#18]
When following your example playbook I get an incorrectly formatted process.yaml file:

```
init_config: null
instances:
-   name: ssh
    search_string:
    - ssh
    - sshd
-   cpu_check_interval: 0.2
    exact_match: true
    ignore_denied_access: true
    name: syslog
    search_string:
    - rsyslog
```

See http://codebeautify.org/yaml-validator for validation. This results in datadog not collecting these statistics.
