### ISSUE TITLE
Actually invalid YAML from datadog_checks

### ISSUE THREAD

**Issue by asciifaceman** [DataDog/ansible-datadog#187]
This was ignored in #72  and is an actual problem that is generating broken configurations that datadog-agent is not honoring.

```
    datadog_checks:
      journal:
        logs:
          - type: journald
            path: /run/log/journal
            service: "blah"
            sourcecategory: "blah"
            tags: "blah"
            exclude_units:
              - session-*.scope
              - datadog-agent.service
              - datadog-agent-process.service
              - datadog-agent-trace.service
              - cron.service
              - sudo.service
              - ssh.service
```

creates (abridged)

```
logs:
-   exclude_units:
    - session-585.scope
    - session-2.scope
    - datadog-agent.service
    - datadog-agent-process.service
    - datadog-agent-trace.service
    - cron.service
    - sudo.service
    - ssh.service
```

Look closely. it's *not* 

```
logs:
- exclude_units:
  - session-585.scope
  - session-2.scope
```

Despite what was said in #72, the behavior described by @olivielpeau is not what is happening. Erroneous spaces are being injected, with the `-` being placed furthest left and the rest of the line being at its proper indent. This entire section gets skipped by datadog-agent when read at startup, in this case exclude_units was entirely ignored, while the rest worked.

**Comment by olivielpeau** [comment]
Thanks for reporting this @asciifaceman. The last 2 yaml snippets you shared should be semantically identical here despite the difference in the number of whitespaces, but there could be discrepancies between yaml parsers.
Have you been able to confirm that the last snippet is correctly interpreted by the Agent, and that the one before isn't?

If so, could you also share the unabridged version of the yaml that's generated? Thanks!

**Comment by asciifaceman** [comment]
@olivielpeau first off, apologies for my tone coming back today I see I was a little mad at the software not anybody.

I've been working on a support case with datadog directly where my journal excludes were not being honored. Returning to it today, it seems intermittent rather than the complete failure I saw before.

Full config written by ansible-datadog:
```
[redacted-staging]$ cat /etc/datadog-agent/conf.d/journal.d/conf.yaml
logs:
-   exclude_units:
    - session-*.scope
    - datadog-agent.service
    - datadog-agent-process.service
    - datadog-agent-trace.service
    - cron.service
    - sudo.service
    - systemd-logind.service
    - ssh.service
    - ifup@eth0.service
    path: /run/log/journal
    service: redacted.redacted.stage
    sourcecategory: redacted
    tags: redacted, redacted, stage
    type: journald
```

Result:

![Screen Shot 2019-04-02 at 10 44 13 AM](https://user-images.githubusercontent.com/1619591/55424140-73bdf500-5534-11e9-8112-baa5a3b8caf6.png)


I guess ultimately seeing it largely work now is either a lack of new logs being generated or an oddity on the side of datadog. I was tackling this indent because datadog 

-----

I did whip up an example to prove that ansible doesn't care about the indentation and maybe shut this up indefinitely for you:

```
---
- name: "Test for issues/187"
  hosts: localhost

  vars:
  -   names:
      - thing1
      - thing2
      - thing 3

  tasks:
    - name: "Debug names"
      delegate_to: localhost
      debug:
        msg: "{{ item }}"
      with_items: "{{ names }}"
```

```
TASK [Debug names] ************************************************************************************************
ok: [localhost -> localhost] => (item=thing1) => {
    "msg": "thing1"
}
ok: [localhost -> localhost] => (item=thing2) => {
    "msg": "thing2"
}
ok: [localhost -> localhost] => (item=thing 3) => {
    "msg": "thing 3"
}
```

There is nothing useful to add and no correlation that I can provide now. I'm thinking the issue I was facing may have been in the agent itself.

Thanks for your time Olivier.
