### ISSUE TITLE
datadog_monitor type: "process alert" no longer working

### ISSUE THREAD

**Issue by asciifaceman** [DataDog/ansible-datadog#219]
I've been using datadog_monitor like the below snippet for some time now, having created hundreds of process alerts this way.

```
    - name: (Migrating) Deploy Prod datadog monitor
      delegate_to: localhost
      datadog_monitor:
        type: "process alert"
        thresholds:
          critical: 0
        name: "A test monitor"
        state: "present"
        query: "redacted query that identifies process"
        message: "alert message"
        api_key: "{{ datadog.apiKey }}"
        app_key: "{{ datadog.appKey }}"
```

Recently, something has changed and it no longer works when a new employee installed the requirements and proceeded.

Recent error: 

```
value of type must be one of: metric alert, service check, event alert, got: process alert
```

This has never occurred before and I'm curious if it was a change in the upstream.

Broken:
Ansible 2.8.4
datadogpy 0.31.0

Working:
ansible 2.6.0
datadogpy 0.26.0
