### ISSUE TITLE
Why is system-probe.yaml owner set as root? 

### ISSUE THREAD

**Issue by rromanchuk** [DataDog/ansible-datadog#238]
Is the regression on this file away from `"{{ datadog_user }}"` intentional?  This causes issues with `datadog-agent` when launching. 

```
- name: Create process agent configuration file
  template:
    src: datadog.conf.j2
    dest: /etc/datadog-agent/process-agent.conf
    owner: "{{ datadog_user }}"
    group: "{{ datadog_group }}"
  notify: restart datadog-agent

- name: Create system-probe configuration file
  template:
    src: system-probe.yaml.j2
    dest: /etc/datadog-agent/system-probe.yaml
    mode: 0640
    owner: "root"
    group: "{{ datadog_group }}"
```

Also warning to anyone trying to set this up. You must start `datadog-agent-system` before `datadog-angent` or you will not get any data forwarded.
