### ISSUE TITLE
YAML Indentation issue using Datadog role

### ISSUE THREAD

**Issue by rdvansloten** [DataDog/ansible-datadog#254]
Hi,

I am using the following playbook to provision Haproxy and process monitoring. Even without putting the check config in a variable, the outcome seems the same. Using Ansible 2.8 and the latest version of the DD role.

```
- hosts: lbs
  become: yes
  roles:
    - { role: Datadog.datadog, become: yes }

  post_tasks:
    - name: Add FQDN
      lineinfile:
        path: /etc/datadog-agent/datadog.yaml
        line: "hostname_fqdn: true"
        create: yes
    
    - name: Replace false FQDN
      replace:
        path: /etc/datadog-agent/datadog.yaml
        regexp: '^hostname_fqdn: false'
        replace: '\1hostname_fqdn: true\2'

    - name: Restart Datadog-Agent
      service:
        name: datadog-agent
        state: restarted
  vars:
    # Custom variables
    dd_api_key: "bla"
    dd_agent_version: "7.16.0"
    dd_checks:
      process:
        init_config:
          instances:
          - name: ssh
            search_string: ['ssh', 'sshd' ]
            exact_match: false
          - name: haproxy
            search_string: ['haproxy']
            exact_match: false
      haproxy:       
        init_config:
          instances:
          - url: http://localhost/admin?stats

    # Role variables
    datadog_api_key: "{{ dd_api_key }}"
    datadog_enabled: "{{ dd_enabled | default(true) }}"
    datadog_agent_version: "{{ dd_agent_version | default(omit) }}"
    datadog_config:
      tags: "{{ tags | default(omit) }}"
      log_level: "{{ log_level | default('INFO') }}"
      apm_config:
        enabled: "{{ apm_enabled | default(false) }}"
        max_traces_per_second: 10
      logs_enabled: "{{ logs_enabled | default(false) }}"
    datadog_checks: "{{ dd_checks | default(omit) }}"
    system_probe_config:
      enabled: "{{ system_probe_enabled | default(false )}}"
```

The issue I'm having is that the indentation in the resulting conf.yaml is wrong (4 spaces, not a tab), even though I am not using this type of spacing in the Ansible playbook.

```
init_config:
    instances:
    -   url: http://localhost/admin?stats
```

```
init_config:
    instances:
    -   exact_match: false
        name: ssh
        search_string:
        - ssh
        - sshd
    -   exact_match: false
        name: haproxy
        search_string:
        - haproxy
```

If I remove the spaces in front of "instances", I get this conf.yaml:

```
init_config: null
instances:
-   exact_match: false
    name: ssh
    search_string:
    - ssh
    - sshd
-   exact_match: false
    name: haproxy
    search_string:
    - haproxy
```

The latter seems to work, but why is this "null" there?

**Comment by KSerrania** [comment]
Hi @rdvansloten,

Thanks for the report!

About the indentation issue: in the role, we don't care about the type of spacing used in the playbook file (as long as the yaml is valid, of course): we take the `datadog_checks[<check>]` object and render it using `to_nice_yaml` (as evidenced here: https://github.com/DataDog/ansible-datadog/blob/master/templates/checks.yaml.j2), which produces a valid yaml file with a 4-space indentation by default.

There seems to be a mistake in your configuration file: `instances` is not a subkey of `init_config`, they are two different keys living on the same level (see the [documentation examples](https://github.com/DataDog/ansible-datadog#configuring-a-check)). Your configuration should thus be:

```
  vars:
    dd_checks:
      process:
        init_config:
        instances:
        - name: ssh
          search_string: ['ssh', 'sshd' ]
          exact_match: false
        - name: haproxy
          search_string: ['haproxy']
          exact_match: false
      haproxy:       
        init_config:
        instances:
        - url: http://localhost/admin?stats
```

In most cases, there's nothing special to put in the `init_config` key so it's left blank, so the rendered yaml will contain `init_config: null` (`to_nice_yaml` replaces blanks by the more explicit `null`, both are valid yaml).
