### ISSUE TITLE
Role does not seam to restart after config change

### ISSUE THREAD

**Issue by michaeldg** [DataDog/ansible-datadog#263]
Hi,

We use this role to install and manage the datadog agent. After we used the role to change the tags in the configuration, these changes were not picked up. This caused a lot of 'production' alerts about development instances.

Please implement a notify in the role so this is no longer the case.

Thanks,
Michaël

**Comment by michaeldg** [comment]
(We restarted the datadog agent to fix this.)

**Comment by KSerrania** [comment]
Hi @michaeldg,

Thanks for the report! Could you give us some more details on your configuration:
- the ansible-datadog role version used,
- the Agent version installed by the role,
- where did you change the tags (was it in the main configuration, or in the configuration of one of the checks?)

**Comment by michaeldg** [comment]
Hey,

The version we used:
```
- src: git+https://github.com/DataDog/ansible-datadog.git
  version: 4.1.1
```

I don't know which version of the agent was installed when the issue occurred, but currently installed is:
```
user@host:~$ dpkg -l |grep datadog
ii  datadog-agent                      1:7.17.0-1                                  amd64        Datadog Monitoring Agent
```

Initially we ran the role with 'environment:prd' as tags, later on we changed the tags. The changes seams to not have picked up. 

As said, a restart fixed this.

**Comment by michaeldg** [comment]
The tags were changed in the main configuration.

**Comment by KSerrania** [comment]
Thanks for the details!

I tried reproducing your issue on an Ubuntu 18.04 host, with ansible-datadog version 4.1.1, applying the two following configs in order:

```
- hosts: servers
  roles:
    - { role: ansible-datadog, become: yes }
  vars:
    datadog_api_key: <API_KEY>
    datadog_config:
      tags:
        - "environment:test"
```

```
- hosts: servers
  roles:
    - { role: ansible-datadog, become: yes }
  vars:
    datadog_api_key: <API_KEY>
    datadog_config:
      tags:
        - "environment:dev"
```

but I couldn't reproduce your issue: after the first run, the Agent reports the `environment:dev` tag, and after the second run, the Agent reports the `environment:dev` tag (no manual restart needed). My ansible run log also indicates that a restart did happen:

```
RUNNING HANDLER [ansible-datadog : restart datadog-agent] **************************************************************************************************************************************************
changed: [self]
```
Indeed, we do already implement a `notify: restart datadog-agent` in the role: https://github.com/DataDog/ansible-datadog/blob/8ccf1573dbdb13bf0875883bdc1704e96f79ef6d/tasks/agent-linux.yml#L16-L22

To be able to troubleshoot this issue better, could you provide the ansible run log for the two runs you did?
