### ISSUE TITLE
Multiple API Keys not in Ansible documentation/role

### ISSUE THREAD

**Issue by rdvansloten** [DataDog/ansible-datadog#277]
Hi,

It is possible to use multiple API keys in Datadog, using the variable `additional_endpoints`, but this parameter does not seem to be documented or implemented for the Ansible role. For now, I've used a filthy hack to make it work:

```
echo "$(cat additional.yml)" >> /etc/datadog-agent/datadog.yaml
```

According to this post, it was added for Puppet. 
https://github.com/DataDog/dd-agent/issues/3396

The support desk only gave me the datadog.yaml instructions, but trying to 1:1 implement this in a playbook doesn't seem to work.

datadog.yaml version:
```
api_key: key
dd_url: "https://app.datadoghq.com"
additional_endpoints:
  "https://app.datadoghq.com": key
apm_config:
    enabled: true
```

Also note that APM data only goes to the non-"additional" endpoint/api key (which is actually perfect in my use case) but I'm not sure if we could have it go to both subscriptions.

**Comment by derekwbrown** [comment]
Hi @rdvansloten 
I apologize for the long delay in responding.  
The `datadog_config` variable accepts arbitrary yaml, and therefore can be used to set the "additional_endpoints" variable.  The following config would work:
```
- hosts: all
  roles:
    - { role: datadog.datadog, become: yes }
  vars:
    datadog_agent_major_version: 7
    datadog_api_key: <original key>
    datadog_config:
      additional_endpoints:
        "https://app.datadoghq.com": "additional_key"
```
