### ISSUE TITLE
Checks YML files are not generated correctly

### ISSUE THREAD

**Issue by aairey** [DataDog/ansible-datadog#28]
When using other checks than process, the http_check for example, the yaml file does not get generated correctly and this is ignored by the dd-agent.
## Example

Source playbook yaml:

```
  - hosts: all
    roles:
      - { role: Datadog.datadog, become: yes }  # On Ansible &lt; 1.9, use `sudo: yes` instead of `become: yes`
    vars:
      datadog_api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
      datadog_config:
        tags: "environment:production, moretags"
        log_level: INFO
      datadog_checks:
        process:
          init_config:
          instances:
            - name: ssh
              search_string: ['ssh', 'sshd' ]
        http:
           init_config:

           instances:
             - name: somewebsite Login Page
               url: https://someurl.com/dispatcher/login.jsp
               timeout: 5

               content_match: 'Login'
               collect_response_time: true
               skip_event: true

               tags:
                 - service:somewebsite
                 - url:someurl.com
```

Generated check yaml:

```
init_config: null
instances:
-   collect_response_time: true
    content_match: Login
    name: somewebsite Login Page
    skip_event: true
    tags:
    - service:somewebsite
    - url:someurl.com
    timeout: 5
    url: https://someurl.com/dispatcher/login.jsp
```

The keys are put in the destination file alphabetically in stead of in order they were specified. (`- name: check_name` is missing)
