### ISSUE TITLE
kafka.yml file not generated correctly

### ISSUE THREAD

**Issue by liammac** [DataDog/ansible-datadog#29]
Copying and pasting the yaml from the kafka.yaml.example produces a yaml file that fans to work with the agent

This is the var I'm passing to the module

```
datadog_config:
      tags: "dcos, {{ ec2_tag_env }}, {{ ec2_tag_Name }}"
      log_level: WARN
    datadog_checks:
          docker_daemon:
              init_config:
              instances:
                  - url: "unix://var/run/docker.sock"
                    collect_images_stats: true
                    collect_image_size: true
                    container_tags: ["image_name", "image_tag", "docker_image"]
          mesos_slave:
              init_config:
                  default_timeout: 10
              instances:
                  - url: "http://{{ ec2_private_ip_address }}:5051"
          kafka:
              instances:
                  - tools_jar_path: /opt/mesosphere/active/java/usr/java/lib/tools.jar
                    process_name_regex: .*Kafka.*
                    java_bin_path: /opt/mesosphere/bin/java
              init_config:
                is_jmx: true

                conf:
                    - include:
                        domain: 'kafka.producer'
                        bean_regex: 'kafka\.producer:type=ProducerRequestMetrics,name=ProducerRequestRateAndTimeMs,clientId=.*'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.producer.request_rate
                    - include:
                        domain: 'kafka.producer'
                        bean_regex: 'kafka\.producer:type=ProducerRequestMetrics,name=ProducerRequestRateAndTimeMs,clientId=.*'
                        attribute:
                        Mean:
                            metric_type: gauge
                            alias: kafka.producer.request_latency_avg
                    - include:
                        domain: 'kafka.producer'
                        bean_regex: 'kafka\.producer:type=ProducerTopicMetrics,name=BytesPerSec,clientId=.*'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.producer.bytes_out
                    - include:
                        domain: 'kafka.producer'
                        bean_regex: 'kafka\.producer:type=ProducerTopicMetrics,name=MessagesPerSec,clientId=.*'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.producer.message_rate


                    - include:
                        domain: 'kafka.producer'
                        bean_regex: 'kafka\.producer:type=producer-metrics,client-id=.*'
                        attribute:
                        response-rate:
                            metric_type: gauge
                            alias: kafka.producer.response_rate
                    - include:
                        domain: 'kafka.producer'
                        bean_regex: 'kafka\.producer:type=producer-metrics,client-id=.*'
                        attribute:
                        request-rate:
                            metric_type: gauge
                            alias: kafka.producer.request_rate
                    - include:
                        domain: 'kafka.producer'
                        bean_regex: 'kafka\.producer:type=producer-metrics,client-id=.*'
                        attribute:
                        request-latency-avi:
                            metric_type: gauge
                            alias: kafka.producer.request_latency_avg
                    - include:
                        domain: 'kafka.producer'
                        bean_regex: 'kafka\.producer:type=producer-metrics,client-id=.*'
                        attribute:
                        outgoing-byte-rate:
                            metric_type: gauge
                            alias: kafka.producer.bytes_out
                    - include:
                        domain: 'kafka.producer'
                        bean_regex: 'kafka\.producer:type=producer-metrics,client-id=.*'
                        attribute:
                        io-wait-time-ns-avg:
                            metric_type: gauge
                            alias: kafka.producer.io_wait


                    - include:
                        domain: 'kafka.consumer'
                        bean_regex: 'kafka\.consumer:type=ConsumerFetcherManager,name=MaxLag,clientId=.*'
                        attribute:
                        Value:
                            metric_type: gauge
                            alias: kafka.consumer.max_lag
                    - include:
                        domain: 'kafka.consumer'
                        bean_regex: 'kafka\.consumer:type=ConsumerFetcherManager,name=MinFetchRate,clientId=.*'
                        attribute:
                        Value:
                            metric_type: gauge
                            alias: kafka.consumer.fetch_rate
                    - include:
                        domain: 'kafka.consumer'
                        bean_regex: 'kafka\.consumer:type=ConsumerTopicMetrics,name=BytesPerSec,clientId=.*'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.consumer.bytes_in
                    - include:
                        domain: 'kafka.consumer'
                        bean_regex: 'kafka\.consumer:type=ConsumerTopicMetrics,name=MessagesPerSec,clientId=.*'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.consumer.messages_in

                    - include:
                        domain: 'kafka.consumer'
                        bean_regex: 'kafka\.consumer:type=ZookeeperConsumerConnector,name=ZooKeeperCommitsPerSec,clientId=.*'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.consumer.zookeeper_commits
                    - include:
                        domain: 'kafka.consumer'
                        bean_regex: 'kafka\.consumer:type=ZookeeperConsumerConnector,name=KafkaCommitsPerSec,clientId=.*'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.consumer.kafka_commits

                    - include:
                        domain: 'kafka.consumer'
                        bean_regex: 'kafka\.consumer:type=consumer-fetch-manager-metrics,client-id=.*'
                        attribute:
                        bytes-consumed-rate:
                            metric_type: gauge
                            alias: kafka.consumer.bytes_in
                    - include:
                        domain: 'kafka.consumer'
                        bean_regex: 'kafka\.consumer:type=consumer-fetch-manager-metrics,client-id=.*'
                        attribute:
                        records-consumed-rate:
                            metric_type: gauge
                            alias: kafka.consumer.messages_in

                    - include:
                        domain: 'kafka.server'
                        bean: 'kafka.server:type=BrokerTopicMetrics,name=BytesOutPerSec'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.net.bytes_out.rate
                    - include:
                        domain: 'kafka.server'
                        bean: 'kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.net.bytes_in.rate
                    - include:
                        domain: 'kafka.server'
                        bean: 'kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.messages_in.rate
                    - include:
                        domain: 'kafka.server'
                        bean: 'kafka.server:type=BrokerTopicMetrics,name=BytesRejectedPerSec'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.net.bytes_rejected.rate

                    - include:
                        domain: 'kafka.server'
                        bean: 'kafka.server:type=BrokerTopicMetrics,name=FailedFetchRequestsPerSec'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.request.fetch.failed.rate
                    - include:
                        domain: 'kafka.server'
                        bean: 'kafka.server:type=BrokerTopicMetrics,name=FailedProduceRequestsPerSec'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.request.produce.failed.rate
                    - include:
                        domain: 'kafka.network'
                        bean: 'kafka.network:type=RequestMetrics,name=RequestsPerSec,request=Produce'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.request.produce.rate
                    - include:
                        domain: 'kafka.network'
                        bean: 'kafka.network:type=RequestMetrics,name=TotalTimeMs,request=Produce'
                        attribute:
                        Mean:
                            metric_type: gauge
                            alias: kafka.request.produce.time.avg
                        99thPercentile:
                            metric_type: gauge
                            alias: kafka.request.produce.time.99percentile
                    - include:
                        domain: 'kafka.network'
                        bean: 'kafka.network:type=RequestMetrics,name=RequestsPerSec,request=FetchConsumer'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.request.fetch_consumer.rate
                    - include:
                        domain: 'kafka.network'
                        bean: 'kafka.network:type=RequestMetrics,name=RequestsPerSec,request=FetchFollower'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.request.fetch_follower.rate
                    - include:
                        domain: 'kafka.network'
                        bean: 'kafka.network:type=RequestMetrics,name=TotalTimeMs,request=FetchConsumer'
                        attribute:
                        Mean:
                            metric_type: gauge
                            alias: kafka.request.fetch_consumer.time.avg
                        99thPercentile:
                            metric_type: gauge
                            alias: kafka.request.fetch_consumer.time.99percentile
                    - include:
                        domain: 'kafka.network'
                        bean: 'kafka.network:type=RequestMetrics,name=TotalTimeMs,request=FetchFollower'
                        attribute:
                        Mean:
                            metric_type: gauge
                            alias: kafka.request.fetch_follower.time.avg
                        99thPercentile:
                            metric_type: gauge
                            alias: kafka.request.fetch_follower.time.99percentile
                    - include:
                        domain: 'kafka.network'
                        bean: 'kafka.network:type=RequestMetrics,name=TotalTimeMs,request=UpdateMetadata'
                        attribute:
                        Mean:
                            metric_type: gauge
                            alias: kafka.request.update_metadata.time.avg
                        99thPercentile:
                            metric_type: gauge
                            alias: kafka.request.update_metadata.time.99percentile
                    - include:
                        domain: 'kafka.network'
                        bean: 'kafka.network:type=RequestMetrics,name=TotalTimeMs,request=Metadata'
                        attribute:
                        Mean:
                            metric_type: gauge
                            alias: kafka.request.metadata.time.avg
                        99thPercentile:
                            metric_type: gauge
                            alias: kafka.request.metadata.time.99percentile
                    - include:
                        domain: 'kafka.network'
                        bean: 'kafka.network:type=RequestMetrics,name=TotalTimeMs,request=Offsets'
                        attribute:
                        Mean:
                            metric_type: gauge
                            alias: kafka.request.offsets.time.avg
                        99thPercentile:
                            metric_type: gauge
                            alias: kafka.request.offsets.time.99percentile
                    - include:
                        domain: 'kafka.server'
                        bean: 'kafka.server:type=KafkaRequestHandlerPool,name=RequestHandlerAvgIdlePercent'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.request.handler.avg.idle.pct.rate
                    - include:
                        domain: 'kafka.server'
                        bean: 'kafka.server:type=ProducerRequestPurgatory,name=PurgatorySize'
                        attribute:
                        Value:
                            metric_type: gauge
                            alias: kafka.request.producer_request_purgatory.size
                    - include:
                        domain: 'kafka.server'
                        bean: 'kafka.server:type=FetchRequestPurgatory,name=PurgatorySize'
                        attribute:
                        Value:
                            metric_type: gauge
                            alias: kafka.request.fetch_request_purgatory.size

                    - include:
                        domain: 'kafka.server'
                        bean: 'kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions'
                        attribute:
                        Value:
                            metric_type: gauge
                            alias: kafka.replication.under_replicated_partitions
                    - include:
                        domain: 'kafka.server'
                        bean: 'kafka.server:type=ReplicaManager,name=IsrShrinksPerSec'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.replication.isr_shrinks.rate
                    - include:
                        domain: 'kafka.server'
                        bean: 'kafka.server:type=ReplicaManager,name=IsrExpandsPerSec'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.replication.isr_expands.rate
                    - include:
                        domain: 'kafka.controller'
                        bean: 'kafka.controller:type=ControllerStats,name=LeaderElectionRateAndTimeMs'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.replication.leader_elections.rate
                    - include:
                        domain: 'kafka.controller'
                        bean: 'kafka.controller:type=ControllerStats,name=UncleanLeaderElectionsPerSec'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.replication.unclean_leader_elections.rate
                    - include:
                        domain: 'kafka.controller'
                        bean: 'kafka.controller:type=KafkaController,name=OfflinePartitionsCount'
                        attribute:
                        Value:
                            metric_type: gauge
                            alias: kafka.replication.offline_partitions_count
                    - include:
                        domain: 'kafka.controller'
                        bean: 'kafka.controller:type=KafkaController,name=ActiveControllerCount'
                        attribute:
                        Value:
                            metric_type: gauge
                            alias: kafka.replication.active_controller_count
                    - include:
                        domain: 'kafka.server'
                        bean: 'kafka.server:type=ReplicaManager,name=PartitionCount'
                        attribute:
                        Value:
                            metric_type: gauge
                            alias: kafka.replication.partition_count
                    - include:
                        domain: 'kafka.server'
                        bean: 'kafka.server:type=ReplicaManager,name=LeaderCount'
                        attribute:
                        Value:
                            metric_type: gauge
                            alias: kafka.replication.leader_count
                    - include:
                        domain: 'kafka.server'
                        bean: 'kafka.server:type=ReplicaFetcherManager,name=MaxLag,clientId=Replica'
                        attribute:
                        Value:
                            metric_type: gauge
                            alias: kafka.replication.max_lag

                    - include:
                        domain: 'kafka.log'
                        bean: 'kafka.log:type=LogFlushStats,name=LogFlushRateAndTimeMs'
                        attribute:
                        Count:
                            metric_type: rate
                            alias: kafka.log.flush_rate.rate

```

And this is what I'm getting out

```
init_config:
    conf:
    -   include:
            Count:
                alias: kafka.producer.request_rate
                metric_type: rate
            attribute: null
            bean_regex: kafka\.producer:type=ProducerRequestMetrics,name=ProducerRequestRateAndTimeMs,clientId=.*
            domain: kafka.producer
    -   include:
            Mean:
                alias: kafka.producer.request_latency_avg
                metric_type: gauge
            attribute: null
            bean_regex: kafka\.producer:type=ProducerRequestMetrics,name=ProducerRequestRateAndTimeMs,clientId=.*
            domain: kafka.producer
    -   include:
            Count:
                alias: kafka.producer.bytes_out
                metric_type: rate
            attribute: null
            bean_regex: kafka\.producer:type=ProducerTopicMetrics,name=BytesPerSec,clientId=.*
            domain: kafka.producer
    -   include:
            Count:
                alias: kafka.producer.message_rate
                metric_type: rate
            attribute: null
            bean_regex: kafka\.producer:type=ProducerTopicMetrics,name=MessagesPerSec,clientId=.*
            domain: kafka.producer
    -   include:
            attribute: null
            bean_regex: kafka\.producer:type=producer-metrics,client-id=.*
            domain: kafka.producer
            response-rate:
                alias: kafka.producer.response_rate
                metric_type: gauge
    -   include:
            attribute: null
            bean_regex: kafka\.producer:type=producer-metrics,client-id=.*
            domain: kafka.producer
            request-rate:
                alias: kafka.producer.request_rate
                metric_type: gauge
    -   include:
            attribute: null
            bean_regex: kafka\.producer:type=producer-metrics,client-id=.*
            domain: kafka.producer
            request-latency-avg:
                alias: kafka.producer.request_latency_avg
                metric_type: gauge
    -   include:
            attribute: null
            bean_regex: kafka\.producer:type=producer-metrics,client-id=.*
            domain: kafka.producer
            outgoing-byte-rate:
                alias: kafka.producer.bytes_out
                metric_type: gauge
    -   include:
            attribute: null
            bean_regex: kafka\.producer:type=producer-metrics,client-id=.*
            domain: kafka.producer
            io-wait-time-ns-avg:
                alias: kafka.producer.io_wait
                metric_type: gauge
    -   include:
            Value:
                alias: kafka.consumer.max_lag
                metric_type: gauge
            attribute: null
            bean_regex: kafka\.consumer:type=ConsumerFetcherManager,name=MaxLag,clientId=.*
            domain: kafka.consumer
    -   include:
            Value:
                alias: kafka.consumer.fetch_rate
                metric_type: gauge
            attribute: null
            bean_regex: kafka\.consumer:type=ConsumerFetcherManager,name=MinFetchRate,clientId=.*
            domain: kafka.consumer
    -   include:
            Count:
                alias: kafka.consumer.bytes_in
                metric_type: rate
            attribute: null
            bean_regex: kafka\.consumer:type=ConsumerTopicMetrics,name=BytesPerSec,clientId=.*
            domain: kafka.consumer
    -   include:
            Count:
                alias: kafka.consumer.messages_in
                metric_type: rate
            attribute: null
            bean_regex: kafka\.consumer:type=ConsumerTopicMetrics,name=MessagesPerSec,clientId=.*
            domain: kafka.consumer
    -   include:
            Count:
                alias: kafka.consumer.zookeeper_commits
                metric_type: rate
            attribute: null
            bean_regex: kafka\.consumer:type=ZookeeperConsumerConnector,name=ZooKeeperCommitsPerSec,clientId=.*
            domain: kafka.consumer
    -   include:
            Count:
                alias: kafka.consumer.kafka_commits
                metric_type: rate
            attribute: null
            bean_regex: kafka\.consumer:type=ZookeeperConsumerConnector,name=KafkaCommitsPerSec,clientId=.*
            domain: kafka.consumer
    -   include:
            attribute: null
            bean_regex: kafka\.consumer:type=consumer-fetch-manager-metrics,client-id=.*
            bytes-consumed-rate:
                alias: kafka.consumer.bytes_in
                metric_type: gauge
            domain: kafka.consumer
    -   include:
            attribute: null
            bean_regex: kafka\.consumer:type=consumer-fetch-manager-metrics,client-id=.*
            domain: kafka.consumer
            records-consumed-rate:
                alias: kafka.consumer.messages_in
                metric_type: gauge
    -   include:
            Count:
                alias: kafka.net.bytes_out.rate
                metric_type: rate
            attribute: null
            bean: kafka.server:type=BrokerTopicMetrics,name=BytesOutPerSec
            domain: kafka.server
    -   include:
            Count:
                alias: kafka.net.bytes_in.rate
                metric_type: rate
            attribute: null
            bean: kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec
            domain: kafka.server
    -   include:
            Count:
                alias: kafka.messages_in.rate
                metric_type: rate
            attribute: null
            bean: kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec
            domain: kafka.server
    -   include:
            Count:
                alias: kafka.net.bytes_rejected.rate
                metric_type: rate
            attribute: null
            bean: kafka.server:type=BrokerTopicMetrics,name=BytesRejectedPerSec
            domain: kafka.server
    -   include:
            Count:
                alias: kafka.request.fetch.failed.rate
                metric_type: rate
            attribute: null
            bean: kafka.server:type=BrokerTopicMetrics,name=FailedFetchRequestsPerSec
            domain: kafka.server
    -   include:
            Count:
                alias: kafka.request.produce.failed.rate
                metric_type: rate
            attribute: null
            bean: kafka.server:type=BrokerTopicMetrics,name=FailedProduceRequestsPerSec
            domain: kafka.server
    -   include:
            Count:
                alias: kafka.request.produce.rate
                metric_type: rate
            attribute: null
            bean: kafka.network:type=RequestMetrics,name=RequestsPerSec,request=Produce
            domain: kafka.network
    -   include:
            99thPercentile:
                alias: kafka.request.produce.time.99percentile
                metric_type: gauge
            Mean:
                alias: kafka.request.produce.time.avg
                metric_type: gauge
            attribute: null
            bean: kafka.network:type=RequestMetrics,name=TotalTimeMs,request=Produce
            domain: kafka.network
    -   include:
            Count:
                alias: kafka.request.fetch_consumer.rate
                metric_type: rate
            attribute: null
            bean: kafka.network:type=RequestMetrics,name=RequestsPerSec,request=FetchConsumer
            domain: kafka.network
    -   include:
            Count:
                alias: kafka.request.fetch_follower.rate
                metric_type: rate
            attribute: null
            bean: kafka.network:type=RequestMetrics,name=RequestsPerSec,request=FetchFollower
            domain: kafka.network
    -   include:
            99thPercentile:
                alias: kafka.request.fetch_consumer.time.99percentile
                metric_type: gauge
            Mean:
                alias: kafka.request.fetch_consumer.time.avg
                metric_type: gauge
            attribute: null
            bean: kafka.network:type=RequestMetrics,name=TotalTimeMs,request=FetchConsumer
            domain: kafka.network
    -   include:
            99thPercentile:
                alias: kafka.request.fetch_follower.time.99percentile
                metric_type: gauge
            Mean:
                alias: kafka.request.fetch_follower.time.avg
                metric_type: gauge
            attribute: null
            bean: kafka.network:type=RequestMetrics,name=TotalTimeMs,request=FetchFollower
            domain: kafka.network
    -   include:
            99thPercentile:
                alias: kafka.request.update_metadata.time.99percentile
                metric_type: gauge
            Mean:
                alias: kafka.request.update_metadata.time.avg
                metric_type: gauge
            attribute: null
            bean: kafka.network:type=RequestMetrics,name=TotalTimeMs,request=UpdateMetadata
            domain: kafka.network
    -   include:
            99thPercentile:
                alias: kafka.request.metadata.time.99percentile
                metric_type: gauge
            Mean:
                alias: kafka.request.metadata.time.avg
                metric_type: gauge
            attribute: null
            bean: kafka.network:type=RequestMetrics,name=TotalTimeMs,request=Metadata
            domain: kafka.network
    -   include:
            99thPercentile:
                alias: kafka.request.offsets.time.99percentile
                metric_type: gauge
            Mean:
                alias: kafka.request.offsets.time.avg
                metric_type: gauge
            attribute: null
            bean: kafka.network:type=RequestMetrics,name=TotalTimeMs,request=Offsets
            domain: kafka.network
    -   include:
            Count:
                alias: kafka.request.handler.avg.idle.pct.rate
                metric_type: rate
            attribute: null
            bean: kafka.server:type=KafkaRequestHandlerPool,name=RequestHandlerAvgIdlePercent
            domain: kafka.server
    -   include:
            Value:
                alias: kafka.request.producer_request_purgatory.size
                metric_type: gauge
            attribute: null
            bean: kafka.server:type=ProducerRequestPurgatory,name=PurgatorySize
            domain: kafka.server
    -   include:
            Value:
                alias: kafka.request.fetch_request_purgatory.size
                metric_type: gauge
            attribute: null
            bean: kafka.server:type=FetchRequestPurgatory,name=PurgatorySize
            domain: kafka.server
    -   include:
            Value:
                alias: kafka.replication.under_replicated_partitions
                metric_type: gauge
            attribute: null
            bean: kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions
            domain: kafka.server
    -   include:
            Count:
                alias: kafka.replication.isr_shrinks.rate
                metric_type: rate
            attribute: null
            bean: kafka.server:type=ReplicaManager,name=IsrShrinksPerSec
            domain: kafka.server
    -   include:
            Count:
                alias: kafka.replication.isr_expands.rate
                metric_type: rate
            attribute: null
            bean: kafka.server:type=ReplicaManager,name=IsrExpandsPerSec
            domain: kafka.server
    -   include:
            Count:
                alias: kafka.replication.leader_elections.rate
                metric_type: rate
            attribute: null
            bean: kafka.controller:type=ControllerStats,name=LeaderElectionRateAndTimeMs
            domain: kafka.controller
    -   include:
            Count:
                alias: kafka.replication.unclean_leader_elections.rate
                metric_type: rate
            attribute: null
            bean: kafka.controller:type=ControllerStats,name=UncleanLeaderElectionsPerSec
            domain: kafka.controller
    -   include:
            Value:
                alias: kafka.replication.offline_partitions_count
                metric_type: gauge
            attribute: null
            bean: kafka.controller:type=KafkaController,name=OfflinePartitionsCount
            domain: kafka.controller
    -   include:
            Value:
                alias: kafka.replication.active_controller_count
                metric_type: gauge
            attribute: null
            bean: kafka.controller:type=KafkaController,name=ActiveControllerCount
            domain: kafka.controller
    -   include:
            Value:
                alias: kafka.replication.partition_count
                metric_type: gauge
            attribute: null
            bean: kafka.server:type=ReplicaManager,name=PartitionCount
            domain: kafka.server
    -   include:
            Value:
                alias: kafka.replication.leader_count
                metric_type: gauge
            attribute: null
            bean: kafka.server:type=ReplicaManager,name=LeaderCount
            domain: kafka.server
    -   include:
            Value:
                alias: kafka.replication.max_lag
                metric_type: gauge
            attribute: null
            bean: kafka.server:type=ReplicaFetcherManager,name=MaxLag,clientId=Replica
            domain: kafka.server
    -   include:
            Count:
                alias: kafka.log.flush_rate.rate
                metric_type: rate
            attribute: null
            bean: kafka.log:type=LogFlushStats,name=LogFlushRateAndTimeMs
            domain: kafka.log
    is_jmx: true
instances:
-   java_bin_path: /opt/mesosphere/bin/java
    process_name_regex: .*Kafka.*
    tools_jar_path: /opt/mesosphere/active/java/usr/java/lib/tools.jar
```

And I'm getting these errors in the logs

```
2016-07-12 00:20:14,049 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: kafka.server:type=ReplicaFetcherManager,name=MaxLag,clientId=Replica : javax.management.MBeanAttributeInfo[description=Attribute exposed for management, name=Value, type=java.lang.Object, read-only, descriptor={}]
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.String
        at org.datadog.jmxfetch.Filter$1.<init>(Filter.java:58)
        at org.datadog.jmxfetch.Filter.toStringArrayList(Filter.java:57)
        at org.datadog.jmxfetch.Filter.getParameterValues(Filter.java:140)
        at org.datadog.jmxfetch.JMXAttribute.matchBeanName(JMXAttribute.java:281)
        at org.datadog.jmxfetch.JMXAttribute.matchBean(JMXAttribute.java:318)
        at org.datadog.jmxfetch.JMXSimpleAttribute.match(JMXSimpleAttribute.java:42)
        at org.datadog.jmxfetch.Instance.getMatchingAttributes(Instance.java:254)
        at org.datadog.jmxfetch.Instance.init(Instance.java:133)
        at org.datadog.jmxfetch.App.init(App.java:354)
        at org.datadog.jmxfetch.App.main(App.java:92)
```

Running jmxfetch.py manually I get

```
 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/jmxfetch.py
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/jmxfetch.py", line 7, in <module>
    from config import initialize_logging  # noqa
  File "/opt/datadog-agent/agent/config.py", line 26, in <module>
    from util import check_yaml, get_os
  File "/opt/datadog-agent/agent/util.py", line 22, in <module>
    import yaml  # noqa, let's guess, probably imported somewhere
  File "/opt/mesosphere/lib/python3.4/site-packages/yaml/__init__.py", line 284
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid syntax
```

**Comment by olivielpeau** [comment]
Hi @liammac!

It looks like there's an error in the configuration you're passing in the var, on the `attribute` key of each `include`.

Instead of:

``` yaml
- include:
    domain: 'kafka.producer'
    bean_regex: 'kafka\.producer:type=ProducerRequestMetrics,name=ProducerRequestRateAndTimeMs,clientId=.*'
    attribute:
    Count:
    metric_type: rate
    alias: kafka.producer.request_rate
```

an instance should read:

``` yaml
- include:
    domain: 'kafka.producer'
    bean_regex: 'kafka\.producer:type=ProducerRequestMetrics,name=ProducerRequestRateAndTimeMs,clientId=.*'
    attribute:
      Count:
        metric_type: rate
        alias: kafka.producer.request_rate
```

i.e., `Count` should be nested under `attribute`, and `metric_type` and `alias` are both nested under `Count`.

Could you change all your `include`s, and let me know if this fixes it? Thanks!
