### ISSUE TITLE
datadog.yaml.j2 problems

### ISSUE THREAD

**Issue by fajfer** [DataDog/ansible-datadog#302]
Hey guys, I'm running Linux machines and having lots of problems with this step:
```
- name: Create main Datadog agent configuration file
  template:
    src: datadog.yaml.j2
    dest: /etc/datadog-agent/datadog.yaml
    owner: "{{ datadog_user }}"
    group: "{{ datadog_group }}"
  notify: restart datadog-agent
```
I'm using the example from README.md, which is:
```
        datadog_config:
          tags:
            - "instance-type:{{ instance-type }}"
            - "zone:{{ location }}"
            - "environment:{{ env }}"
            - "client:{{ client }}"
            - "provider:{{ provider }}"
          log_level: INFO
          apm_config:
            enabled: true
            max_traces_per_second: 10
          logs_enabled: false
```
instance-type, location, env, client and provider are inventory variables, just left what I'm using as-is.

I didn't bother using datadog_config earlier, without mentioning it the role was always flawless for me, but when running configuration above I'm getting these kind of errors on each machine:
```
FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'instance' is undefined"}
```
I'm guessing this instruction is generating errors:
```
{% if datadog_config is defined and datadog_config|length > 0 -%}
{{ datadog_config | to_nice_yaml }}
{% endif %}
```
It kinda doesn't work right, too as if something is null (datadog_config) this will just fail as well. I'm kinda complaining on this thread as I'm testing datadog out but it looks like it wasn't really tested correctly, or I'm doing some rookie-level mistakes and I'm not aware of it
