### ISSUE TITLE
System Probe Config fails when enabling network_config

### ISSUE THREAD

**Issue by lognarly** [DataDog/ansible-datadog#330]
When trying to enable NPM on Linux systems, I am getting a failure when trying to set the following:

network_config:
  enabled: true

Role being called by playbook. Everything else works as needed.

```
- name: Install Datadog Agent - JAVA
  include_role:
    name: datadog.datadog
    tasks_from: main
  vars:
    datadog_config: "{{ datadog_agent_config_java }}"
    system_probe_config:
      sysprobe_socket: /opt/datadog-agent/run/sysprobe.sock
    network_config:
      enabled: true
    datadog_checks: "{{ datadog_java_config }}"
```
Error:
```
FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'enabled'\n\nThe error appears to be in '/Users/logan/.ansible/roles/datadog.datadog/tasks/agent-linux.yml': line 95, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: set system probe enabled\n  ^ here\n"}
```

The flag used to be:
```
system_probe_config:
  enabled: true
```

Using ansible [core 2.11.0b3]
