### ISSUE TITLE
Compatibility with installing Marketplace integrations via Ansible role

### ISSUE THREAD

**Issue by lognarly** [DataDog/ansible-datadog#344]
I was wondering if there were plans to allow Marketplace integrations to be installed via the ansible role?

**Comment by bkabrda** [comment]
Hi 👋 thanks for opening the issue!

If I'm not mistaken, Marketplace integrations are considered third-party integrations and so you can install them right now using e.g.:

```
  datadog_integration:
    datadog_rapdev_maxdb:
      action: install
      version: 1.0.0
      third_party: true
```

Is this what you're looking for?
