### ISSUE TITLE
 instrument datadog agent by the location of logs file

### ISSUE THREAD

**Issue by Hamza-Aziz** [DataDog/ansible-datadog#356]
```
`   - name: install the agent on targets`
         ` include_role:`
            name: datadog.datadog
          vars: 
            datadog_api_key: "myApiKey"
            datadog_site: "datadoghq.com"
            datadog_config:
              log_level: INFO
              apm_config:
                enabled: true
              logs_enabled: true
# i think the probleme come from the logs section
              logs:
                - type: file
                  path: /home/ubuntu/web-app/tomcatlogs/logs/*.log
                  service: myapp
                  source: tomcat`
```
i'm trying to instrument datadog agent with datadog Ansible role but i can't figure out why the logs are not reported to datadog ui
