### ISSUE TITLE
Windows C:\\ProgramData\\Datadog\\datadog.yaml not found

### ISSUE THREAD

**Issue by varnav** [DataDog/ansible-datadog#378]
My playbook:

```
- hosts: windows
  roles:
    - role: datadog.datadog
  vars:
    datadog_api_key: "censored"
```

Error I am getting:

```

TASK [datadog.datadog : Create main Datadog agent configuration file] *********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: b'C:\\ProgramData\\Datadog\\datadog.yaml'
```

My user has no permissions for the file. If I manually RDP to machine and fix permissions to a `datadog.yaml` - no, no effect unfortunately.

Windows 2019 Enterprise
Ansible 2.11.2
