### ISSUE TITLE
Ensure configuration directories task fails

### ISSUE THREAD

**Issue by caleb15** [DataDog/ansible-datadog#380]
Ansible version 2.7. I ran it against a ubuntu machine.

vars:
```yml
    datadog_api_key: "{{ lookup('env', 'DATADOG_API_KEY') }}"
    datadog_site: "datadoghq.com"
    datadog_config:
      env: "{{ lookup('env', 'VPC_NAME') }}"
      apm_config:
        enabled: false
      logs_enabled: true
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd' ]
      fluentd:
        init_config:
        instances:
          - monitor_agent_url: localhost:24220/api/plugins.json
```

Ansible log:
```
TASK [datadog.datadog : Ensure configuration directories are present for each Datadog check] ********************************************************************************************************************
Thursday 05 August 2021  10:10:26 -0700 (0:00:00.049)       0:00:41.802 *******
Thursday 05 August 2021  10:10:26 -0700 (0:00:00.049)       0:00:41.802 *******
failed: [bastion] (item=['[', '{', "'", 'p', 'r', 'o', 'c', 'e', 's', 's', "'", ':', ' ', '{',  ... output truncated
```

For some reason it interprets it as a string and then tries to split the string into individual characters. I fixed it by commenting out the `Defend against defined but null datadog_checks variable` task but then I got a new error:

```
TASK [datadog.datadog : Create a configuration file for each Datadog check] *************************************************************************************************************************************
task path: /mnt/f/fifteen5-deploy/roles/datadog.datadog/tasks/agent-linux.yml:70
Thursday 05 August 2021  11:15:15 -0700 (0:00:00.520)       0:00:15.639 *******
Thursday 05 August 2021  11:15:15 -0700 (0:00:00.520)       0:00:15.638 *******
failed: [bastion] (item=['process', 'fluentd']) => {"changed": false, "item": "['process', 'fluentd']", "msg": "RepresenterError: ('cannot represent an object', Undefined)"}
```

I then fixed that error by changing the relevant task to be multiple tasks with hardcoded check names.
