### ISSUE TITLE
compliance_config support

### ISSUE THREAD

**Issue by sfuerte** [DataDog/ansible-datadog#385]
Hello,

Is it possible to add `compliance_config` option support to the role?

**Comment by bkabrda** [comment]
Hi 👋 thanks for opening this issue. Since `compliance_config` is a key expected to be present in `/etc/datadog-agent/datadog.yaml`, have you tried setting it through `datadog_config`, such as this:

```
  vars:
    datadog_api_key: <your_key>
    datadog_config:
      compliance_config:
        enabled: true
        # and other settings
```

This should do the trick. Let me know if this helped. Thanks!
