### ISSUE TITLE
PHP-FPM check being created as php-fpm.yaml and so not being picked up

### ISSUE THREAD

**Issue by ollyculverhouse** [DataDog/ansible-datadog#40]
Hello!

I have a php-fpm check which has been added as below:

```
datadog_checks:
      php-fpm:
        init_config:
        instances:
          - status_url: http://127.0.0.1/php-status
            ping_url: http://127.0.0.1/ping
            ping_reply: pong
```

The weird thing was that the check wasn't being picked up by datadog. I had a quick look in the agent conf.d folder and noticed that there were two php-fpm related files, one called php_fpm.yaml.example and one called php-fpm.yaml (notice the hyphen and not an underscore).
I ran the info command on the agent and noticed that the php-fpm check wasn't being picked up.

I noticed that your integration docs say that the file should be php_fpm.yaml and so renamed php-fpm.yaml to php_fpm.yaml, restarted the agent and all works fine!

Could it be something to do with how the to_nice_yaml module works as per here, when it comes to checks with hyphens in them? https://github.com/DataDog/ansible-datadog/blob/master/templates/checks.yaml.j2

I can of course work round this but this involves having an extra task in ansible, specifically to rename the file.

Running Ansible 2.2.0.0
