### ISSUE TITLE
Unhandled exception occured while templating in task

### ISSUE THREAD

**Issue by albuch** [DataDog/ansible-datadog#401]
Datadog installation role somehow fails for one of its tasks. This used to work, and there are no code config changes related to the datadog agent installation or configuration in our ansible scripts. 

# Error message
```
TASK [Datadog.datadog : Defend against defined but null datadog_checks variable] *************************************************************************************************************************
task path: /Users/xxxxxxx/.ansible/roles/Datadog.datadog/tasks/sanitize-checks.yml:1
fatal: [twistlock]: FAILED! => {
    "msg": "An unhandled exception occurred while templating '{'disk': {'init_config': None, 'instances': [{'name': 'xxxxxxxxxx', 'use_mount': False, 'mount_point_blacklist': ['/var/lib/docker/containers/.*', '/var/lib/docker/overlay2/.*']}]}, 'prometheus': {'init_config': None, 'instances': [{'name': 'xxxxxxxx', 'prometheus_url': 'https://prometheus-user:{{ twistlock_prometheus_user_password | urlencode() }}@txxxxxxxxxxx/api/v1/metrics', 'namespace': 'prometheus', 'metrics': ['twistlock_*', 'go*', 'process*'], 'max_returned_metrics': 100}]}, 'docker': {'init_config': None, 'instances': [{'name': 'xxxxxxxxxxx'}]}}'. Error was a <class 'ValueError'>, original message: not enough values to unpack (expected 2, got 1)"
}
```
Enabling verbose logging `-vvv` didn't show any more info.

# Datadog Agent Config
```
datadog_api_key: "{{datadog_api_key_vaulted}}"
datadog_site: "datadoghq.eu"
datadog_config:
  hostname: "xxxxxxx
  tags: "Owner:xxxxxx"
  log_level: INFO
  apm_config:
    enabled: false
  logs_enabled: false
  process_config:
    enabled: "true"
    scrub_args: true
    custom_sensitive_words: ['*password*','dd_api_key']
datadog_additional_groups: docker
datadog_checks:
  disk:
    init_config:
    instances:
      - name: 'xxxxxxxxx'
        use_mount: false
        mount_point_blacklist:
          - /var/lib/docker/containers/.*
          - /var/lib/docker/overlay2/.*
  prometheus:
    init_config:
    instances:
      - name: 'xxxxxxxxx'
        prometheus_url: "https://prometheus-user:{{ twistlock_prometheus_user_password | urlencode() }}@xxxxxxxxx/api/v1/metrics"
        namespace: 'prometheus'
        metrics:
          - 'twistlock_*'
          - 'go*'
          - 'process*'
        max_returned_metrics: 100
  docker:
    init_config:
    instances:
      - name: 'xxxxxxx'
```

I can't figure out from the error message what the issue is. We use the following versions of ansible and ansible-datadog.
```
% ansible --version
ansible [core 2.11.6] 
  config file = None
  configured module search path = ['/Users/xxxxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/xxxxxx/Library/Python/3.9/lib/python/site-packages/ansible
  ansible collection location = /Users/xxxxxxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/xxxxxxxx/Library/Python/3.9/bin/ansible
  python version = 3.9.7 (default, Oct 12 2021, 22:38:23) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.2
  libyaml = True
% ansible-galaxy list
# /Users/xxxxxx/.ansible/roles
- datadog.datadog, 4.12.0
[WARNING]: - the configured path /usr/share/ansible/roles does not exist.
[WARNING]: - the configured path /etc/ansible/roles does not exist.
```
