### ISSUE TITLE
Wrong formatting for windows_service

### ISSUE THREAD

**Issue by morro-tr** [DataDog/ansible-datadog#402]
Using the below yaml part for windows_service produces wrong conf.yml after deploying through Ansible.

```
datadog_checks: 
  windows_service:
    instances:
      - services:
          - xxxxx
```

Produce the following windows_service.d\conf.yml :

```
instances:
-   services:
    - xxxxx
```

This leads to the configuration for the windows service integration failing.
reproduces every time on Datadog agent 7, using Ansible Galaxy 2.9.4.
