### ISSUE TITLE
restart datadog-handler permission denied

### ISSUE THREAD

**Issue by oliryde** [DataDog/ansible-datadog#41]
After updating a basic check it fails to restart the agent.

`fatal: [hostname]: FAILED! => {"changed": false, "failed": true, "msg": "start-stop-daemon: warning: failed to kill 23378: Operation not permitted\nTraceback (most recent call last):\n  File \"/opt/datadog-agent/bin/supervisord\", line 11, in <module>\n    load_entry_point('supervisor==3.3.0', 'console_scripts', 'supervisord')()\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/supervisor/supervisord.py\", line 365, in main\n    go(options)\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/supervisor/supervisord.py\", line 375, in go\n    d.main()\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/supervisor/supervisord.py\", line 78, in main\n    info_messages)\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/supervisor/options.py\", line 1398, in make_logger\n    stdout = self.nodaemon,\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/supervisor/loggers.py\", line 346, in getLogger\n    handlers.append(RotatingFileHandler(filename,'a',maxbytes,backups))\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/supervisor/loggers.py\", line 172, in __init__\n    FileHandler.__init__(self, filename, mode)\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/supervisor/loggers.py\", line 98, in __init__\n    self.stream = open(filename, mode)\nIOError: [Errno 13] Permission denied: '/var/log/datadog/supervisord.log'\nstart-stop-daemon: warning: failed to kill 23378: Operation not permitted\n"}`

**Comment by olivielpeau** [comment]
Hi @oliryde, it looks like the agent failed to restart because of a permission issue on a log file of the Agent.

1. Could you make sure that you're running the role as `root`? (i.e. with `become: yes`, or with `sudo: yes` for Ansible<1.9)
2. If the issue persists, could send a [flare](https://github.com/DataDog/dd-agent/wiki/Send-logs-to-support-using-flare) to our support team? This should give us enough information to troubleshoot the issue in more details.

Thanks!

**Comment by oliryde** [comment]
Here is my example config.
```yaml
- hosts: hostname
  roles:
    - {role: Datadog.datadog, become: yes}
  vars:
    datadog_checks:
      http_check:
        init_config:
        instances:
          - name: example
            url: http://example.org
            timeout: 1
            collect_response_time: true
            allow_redirects: true
            content_match: 'Example Domain'
            skip_event: true
```

It looks to me like the handler responsible for restarting the agent is not affected by the "become: yes" of the role. If I add it to the handler ([like this](https://github.com/oliryde/ansible-datadog/blob/master/handlers/main.yml)) it runs without failures.

```log
RUNNING HANDLER [Datadog.datadog : restart datadog-agent] **********************
changed: [hostname]
```
