### ISSUE TITLE
/opt/datadog-agent/run/sysprobe.sock: no such file or directory

### ISSUE THREAD

**Issue by marcantoinegodde** [DataDog/ansible-datadog#423]
Hello,

I configured my Ansible task this way:
```
- name: Install the datadog agent
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ VR_datadog_api_key }}"
    datadog_config:
      hostname: "{{ inventory_hostname }}"
      tags: "{{ ['type:'] | product(group_names) | map('join') | list }}"
      process_config:
        enabled: true
      logs_enabled: "{{ ( (global_monitoring_options | intersect(collect_logs) ) != [] if global_monitoring_options is defined else false ) or ( (monitoring_options | intersect(collect_logs) ) != [] if monitoring_options is defined else false ) }}"
      use_dogstatsd: "{{ inventory_hostname in enable_dogstatsd }}"
      network_config:
        enabled: true
```

This doesn't create the required socket file sysprobe.sock like it would have done if I had modified system-prob.yaml. I have this error:
```
============
System Probe
============
  System Probe is not running:

    Errors
    ======
    error setting up remote system probe util, socket path does not exist: stat /opt/datadog-agent/run/sysprobe.sock: no such file or directory
```

Thanks.

**Comment by marcantoinegodde** [comment]
I found my mistake. Sorry.

Should be this way:

```
- name: Install the datadog agent
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ VR_datadog_api_key }}"
    datadog_config:
      hostname: "{{ inventory_hostname }}"
      tags: "{{ ['type:'] | product(group_names) | map('join') | list }}"
      process_config:
        enabled: true
      logs_enabled: "{{ ( (global_monitoring_options | intersect(collect_logs) ) != [] if global_monitoring_options is defined else false ) or ( (monitoring_options | intersect(collect_logs) ) != [] if monitoring_options is defined else false ) }}"
      use_dogstatsd: "{{ inventory_hostname in enable_dogstatsd }}"
    network_config:
      enabled: true
```
