### ISSUE TITLE
Oracle integration configuration

### ISSUE THREAD

**Issue by edvinas31** [DataDog/ansible-datadog#433]
Ansible datadog version I am using: https://github.com/DataDog/ansible-datadog/releases/tag/4.11.0

Hi, when trying to add custom query like shown here https://docs.datadoghq.com/integrations/oracle/?tab=linux#example I get the ../oracle.d/conf.yaml file corrupted. When adding to the ansible code the following:

```
- name: Install Datadog
    import_role:
      name: datadog.datadog
    vars:
      datadog_api_key: "{{ credentials_vault['datadoghq.eu']['api_key_' + oci_tag_env_type] }}"
      datadog_site: "datadoghq.eu"
      datadog_agent_major_version: "6"
      datadog_additional_groups:
        - docker
      datadog_checks:
        oracle:
          init_config:
          
          instances:
            - server: localhost:1521
              service_name: tia
              username: datadog
              password: "{{ cust_vault[cust_name][env_name]['tia_db_datadog_password'] }}"
              jdbc_driver_path: "{{ oracle_home.stdout }}/jdbc/lib/ojdbc8.jar"
              only_custom_queries: true
              # min_collection_interval: 15
              protocol: TCP

              custom_queries:
                - metric_prefix: oracle
                  # Check for tablespace usage for 30 mins and group them by tablespace
                  query:
                     select to_binary_float(used_percent),to_binary_float(TABLESPACE_SIZE), to_binary_float(USED_SPACE), TABLESPACE_NAME from sys.dba_tablespace_usage_metrics where used_percent > 20
                  columns:
                    - name: tablespace_usage_count
                      type: gauge
                    - name: used_percent
                      type: tag
                    - name: TABLESPACE_SIZE
                      type: tag
                    - name: TABLESPACE_NAME
                      type: tag
      datadog_config:
        process_config:
          enabled: "true"
        hostname_fqdn: true
        tags:
          - client:{{ cust_name }}
          - env:{{ oci_tag_env_type }}
          - os:linux:{{ ansible_facts.distribution }}
    when:
      - cust_name is defined
      - oci_tag_env_type is defined
      - env_name is defined
    tags: datadog
```

In configuration block I get file wrongly configured:

```
[root@paasdev-db01 esu]# cat /etc/datadog-agent/conf.d/oracle.d/conf.yaml
init_config: null
instances:
-   custom_queries:
    -   columns:
        -   name: tablespace_usage_count
            type: gauge
        -   name: used_percent
            type: tag
        -   name: TABLESPACE_SIZE
            type: tag
        -   name: TABLESPACE_NAME
            type: tag
        metric_prefix: oracle
        query: |-
            select to_binary_float(used_percent),to_binary_float(TABLESPACE_SIZE), to_binary_float(USED_SPACE), TABLESPACE_NAME from sys.dba_tablespace_usage_metrics where used_percent > 20
    jdbc_driver_path: /u01/app/oracle/product/19.0.0/dbhome_1/jdbc/lib/ojdbc8.jar
    only_custom_queries: true
    password: PAAS_DEV#datadog
    protocol: TCP
    server: localhost:1521
    service_name: tia
    username: datadog
```

Could you tell me why the template is switched places?

What I expect to see is:

```
[root@paasdev-db01 esu]# cat /etc/datadog-agent/conf.d/oracle.d/conf.yaml
init_config: null
instances:
-  server: localhost:1521
    jdbc_driver_path: /u01/app/oracle/product/19.0.0/dbhome_1/jdbc/lib/ojdbc8.jar
    only_custom_queries: true
    password: PAAS_DEV#datadog
    protocol: TCP
    service_name: tia
    username: datadog
    custom_queries:
      - metric_prefix: oracle
        # Check for tablespace usage for 30 mins and group them by tablespace
        query:
           select to_binary_float(used_percent),to_binary_float(TABLESPACE_SIZE), to_binary_float(USED_SPACE), TABLESPACE_NAME from sys.dba_tablespace_usage_metrics where used_percent > 20
        columns:
          - name: tablespace_usage_count
            type: gauge
          - name: used_percent
            type: tag
          - name: TABLESPACE_SIZE
            type: tag
          - name: TABLESPACE_NAME
            type: tag
```
