### ISSUE TITLE
Append tags to datadog.yaml instead of overwriting it with a new file.

### ISSUE THREAD

**Issue by tostroski** [DataDog/ansible-datadog#434]
I am trying to simplify our datadog rollout with ansible.  I am running into an issue where I need multiple data_dog checks on the same host and when the second integration gets installed, it wipes out my main agent datadog.yaml file.  

Here is the stripped down example of my playbook:
```
- name: Deploy Datanode Integration
  hosts: node
  roles:
    - { role: datadog.datadog }
  vars:
    datadog_api_key: "{{ dd_api_key }}"
    datadog_agent_version: "{{ dd_agent_version }}"
    datadog_config:
      tags:
        - service:hdfs_datanode
      logs_enabled: false  # available with Agent v6 and v7
    datadog_checks:
      hdfs_datanode:
        init_config:
        instances:
          - hdfs_datanode_jmx_uri: http://{{ inventory_hostname }}:{{ port }}

- name: Deploy Kafka Integration
  hosts: kafka
  roles:
    - { role: datadog.datadog }
  vars:
    datadog_api_key: "{{ dd_api_key }}"
    datadog_agent_version: "{{ dd_agent_version }}"
    datadog_config:
      tags:
        - service:kafka
      logs_enabled: false  # available with Agent v6 and v7
    datadog_checks:
      kafka:
        init_config:
            is_jmx: true
            collect_default_metrics: true
            new_gc_metrics: true
        instances:
          - host: "{{ inventory_hostname }}"
            port: {{ port }}
```
The issue is that if a host belongs to both the node group and the kafka group, the node groups tags get wiped out when the kafka group runs.

Is there a way to append the tags in the datadog.yaml file or is there a better way to do this?

Thanks!
