### ISSUE TITLE
WIndows specific task FAILED when run playbook for linux

### ISSUE THREAD

**Issue by andrewozh** [DataDog/ansible-datadog#450]
I'm trying to install `datadog-agent` with `datadog-puma` integration on a completely new clean ubuntu 16.04 host!

Here's my playbook:

```
---
- name: Install Datadog Agent
  # hosts: all
  hosts: testing
  become: true
  user: ubuntu

  roles:
    - { role: Datadog.datadog, become: yes }
  vars:
    datadog_enabled: false
    datadog_integration:
      datadog-puma:
        action: install
        version: 1.2.0
```

Result:

```
. . .
TASK [Datadog.datadog : macOS Configuration Tasks] *****************************************************************************************************************************
skipping: [drct-testing-dev-0]

TASK [Datadog.datadog : Integrations Tasks] ************************************************************************************************************************************
fatal: [drct-testing-dev-0]: FAILED! => {"reason": "couldn't resolve module/action 'win_command'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/Users/andrewozhegov/.ansible/roles/Datadog.datadog/tasks/integration.yml': line 52, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Removing integrations (Windows)\n  ^ here\n"}

RUNNING HANDLER [Datadog.datadog : restart datadog-agent] **********************************************************************************************************************

PLAY RECAP *********************************************************************************************************************************************************************
drct-testing-dev-0         : ok=62   changed=11   unreachable=0    failed=1    skipped=42   rescued=0    ignored=0
```

Since I'm using macOS & host running ubuntu, there is no sense to install `ansible.windows` collection, as mentioned in docs! Am I doing something wrong?
