### ISSUE TITLE
Format `datadog.conf` with the INI format instead of YAML

### ISSUE THREAD

**Issue by olivielpeau** [DataDog/ansible-datadog#49]
See example in https://github.com/DataDog/dd-agent/issues/3227

The `datadog.conf` file should be formatted as an INI file instead of YAML here: https://github.com/DataDog/ansible-datadog/blob/1.2.0/templates/datadog.conf.j2#L17

cc @pahaz who reported the issue in the linked issue

**Comment by rkonrath** [comment]
Hi,
I had the same problem with this template:
https://github.com/DataDog/ansible-datadog/blob/master/templates/checks.yaml.j2

So, I fixed it temporary:
`-{{ datadog_checks[item] | to_nice_yaml }}`
`+{{ datadog_checks[item] | to_json | from_json | to_nice_yaml }}`

**Comment by pahaz** [comment]
Any news?

**Comment by wawrzek** [comment]
I couldn't define hostname: {{ ansible_hostname }} in config. It might be related to Ansible bug (https://github.com/ansible/ansible/issues/20253).

**Comment by mliljedahl** [comment]
A workaround is to remove the spaces between the commas when for example defining tags.

**Example from playbook**
```
- hosts: webservers
  become: true
  roles:
    - role: datadog
      datadog_api_key: "{{ datadog_api_key }}"
      datadog_config:
        tags: "environment:production,group:webservers,datacenter:europe,provider:gce"
```
