### ISSUE TITLE
Playbook will not pickup variables for haproxy logs forwarding. 

### ISSUE THREAD

**Issue by bnjeongwo** [DataDog/ansible-datadog#491]
What task specifically populates /etc/datadog-agent/conf.d/haproxy.d/conf.yaml

**Comment by bnjeongwo** [comment]
## this is how my haproxy vars_file looks. I am not sure why the playbook is not picking up the logs vars to populate /etc/datadog-agent/conf.d/haproxy.d/conf.yaml

```yaml
---
datadog_checks:
  haproxy:
    init_config:
    instances:
      - url: "https://127.0.0.1:8080/stats"
        tls_verify: xxxx
        tls_ignore_warning: xxxx
  logs:
    - type: file
      path: /var/log/haproxy-traffic.log
      service: my_haproxy_service
      source: haproxy
      sourcecategory: http_web_access
```

**Comment by alopezz** [comment]
I took the liberty of editing your comment to use code formatting so that indentation can be looked at (as it's quite critical in yaml). It looks like the whole `logs` key requires some further indentation, i.e.:

```yaml
datadog_checks:
  haproxy:
    init_config:
    instances:
      - url: "https://127.0.0.1:8080/stats"
        tls_verify: xxxx
        tls_ignore_warning: xxxx
    logs:
      - type: file
        path: /var/log/haproxy-traffic.log
        service: my_haproxy_service
        source: haproxy
        sourcecategory: http_web_access
```

I'll be closing this now; note that contacting [Datadog support](https://help.datadoghq.com/) can be much more effective at getting a response for this sort of issue.
