### ISSUE TITLE
The generated integration configs don't honor the order set in the playbook

### ISSUE THREAD

**Issue by mazlumatabey** [DataDog/ansible-datadog#548]
![image](https://github.com/DataDog/ansible-datadog/assets/49592465/500e8148-b6d9-4363-a6b7-140532400aeb)
Datadog rabbitmq node configuration will generate a wrong config.yaml file when we use node in datadog_checks variable.

Example:
```
datadog_checks:
  rabbitmq:
    init_config:
      service: rabbitmq_redis
    instances:
      - rabbitmq_api_url: http://localhost:15672/api/
        rabbitmq_user: My_user
        rabbitmq_pass: mypassword
        vhosts:
          - my_vhost
        nodes:
          - redis_cluster_node
```
 
 Will generate this wrong config.yaml file:
 
```
 init_config:
  service: rabbitmq_redis
instances:
- nodes:
  - redis_cluster_node
  rabbitmq_api_url: http://localhost:15672/api/
  rabbitmq_pass: mypassword
  rabbitmq_user: My_user
  vhosts:
  - my_vhost
```

When we expect this config.yaml file:

```
init_config:
  service: rabbitmq_redis
instances:
- rabbitmq_api_url: http://localhost:15672/api/
  rabbitmq_pass: mypassword
  rabbitmq_user: My_user
  vhosts:
  - my_vhost
  nodes:
  - redis_cluster_node
```

When using the "nodes" key, Ansible treats it as a re-organization of the elements in the data structure. Instead of simply renaming the key, Ansible considers it a new key with an associated value, and it re-arranges the other keys around this new key in the YAML output.

PS: check about map('combine') in ansible.
