### ISSUE TITLE
Calling datadog.datadog role or datadog.dd.agent role on Debian 12 results in 'datadog-installer is-installed datadog-agent' No such file or directory error

### ISSUE THREAD

**Issue by alexn-cyber** [DataDog/ansible-datadog#623]
Hey folks, 

I'm trying to install Datadog Agent on a debian 12 VM. I'm currently getting the following error that is killing the install

```yaml
TASK [datadog.dd.agent : Bootstrap the installer] *******************************************************************
changed: [p1lrvjb01]

TASK [datadog.dd.agent : Check if installer owns datadog-agent package] *********************************************
fatal: [p1lrvjb01]: FAILED! => {"changed": true, "cmd": "datadog-installer is-installed datadog-agent", "failed_when_result": true, "msg": "[Errno 2] No such file or directory: b'datadog-installer'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

Here is how I am having Ansible call the role. 

```yaml
- name: Ensure Datadog role is applied with elevated privileges
  become: true
  block:
    - name: Call the wrapped datadog.datadog role
      ansible.builtin.include_role:
        name: "{{ 'datadog.datadog' if ansible_facts['os_family'] == 'Windows' else 'datadog.dd.agent' }}" # datadog.dd.agent someday when windows does not hang on gather facts
      vars: # https://github.com/DataDog/ansible-datadog?tab=readme-ov-file#role-variables
        datadog_api_key: "{{ onepassword_dd_apikey.field.value }}"
        datadog_agent_major_version: 7
        datadog_config: # https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml
          site: us5.datadoghq.com
          hostname: "{{ hostvars[inventory_hostname].tags.Name if hostvars[inventory_hostname].tags.Name is defined else (custom_datadog_hostname if custom_datadog_hostname is defined else '') }}"
          host_aliases: # https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml
            # https://docs.datadoghq.com/agent/faq/how-datadog-agent-determines-the-hostname/?tab=agentv6v7#host-aliases
            - '{{ hostvars[inventory_hostname].public_ip_address|default("") }}'
            # TODO PUT THE instance ID here when available
          tags: "{{ datadog_default_tags }}"
          process_config:
            enabled: "true" # type needs to be a string
          apm_config:
            enabled: "false" # type needs to be a string
        datadog_remote_updates: true
        datadog_checks:
          process:
            init_config:
            instances:
              - name: ssh
                search_string: ["ssh", "sshd"]
```
