### ISSUE TITLE
Encountering unexpected keyword argument 'cert_file' error at task Download url to import key task

### ISSUE THREAD

**Issue by alexn-cyber** [DataDog/ansible-datadog#633]
Hello all,

I'm encountering this error running on an Ubuntu 24.04 LTS host with the following settings:

```yaml

- name: (Non-Windows) Call the wrapped datadog.dd.agent role
      ansible.builtin.include_role:
        name: datadog.dd.agent
      vars: # https://github.com/DataDog/ansible-datadog?tab=readme-ov-file#role-variables
        datadog_api_key: "{{ onepassword_dd_apikey.field.value }}"
        datadog_agent_major_version: 7
        datadog_apm_instrumentation_enabled: host
        datadog_config: # https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml
          site: us5.datadoghq.com
          hostname: "{{ hostvars[inventory_hostname].tags.Name if hostvars[inventory_hostname].tags.Name is defined else (custom_datadog_hostname if custom_datadog_hostname is defined else '') }}"
          host_aliases: # https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml
            # https://docs.datadoghq.com/agent/faq/how-datadog-agent-determines-the-hostname/?tab=agentv6v7#host-aliases
            - '{{ hostvars[inventory_hostname].public_ip_address|default("") }}'
            # TODO PUT THE instance ID here when available
          tags: "{{ datadog_default_tags }}"
          process_config:
            enabled: "true" # type needs to be a string
          apm_config:
            enabled: "{{ datadog_enable_apm }}" # type needs to be a string
        datadog_remote_updates: true
        datadog_checks:
          process:
            init_config:
            instances:
              - name: ssh
                search_string: ["ssh", "sshd"]
      when:
        - ansible_facts['os_family'] != 'Windows'

```

```bash

TASK [datadog.dd.agent : Download url to import key. url,key = ('https://s3.amazonaws.com/public-signing-keys/DATADOG_APT_KEY_CURRENT.public', 'DATADOG_APT_KEY_CURRENT')] ***
fatal: [royal_haze]: FAILED! => {"changed": false, "dest": "/tmp/ansible.t4pfuu34keys/DATADOG_APT_KEY_CURRENT", "elapsed": 0, "msg": "An unknown error occurred: HTTPSConnection.__init__() got an unexpected keyword argument 'cert_file'", "url": "https://s3.amazonaws.com/public-signing-keys/DATADOG_APT_KEY_CURRENT.public"}

```
