### ISSUE TITLE
ansible role does not provide an option to override the datadog installer package default version

### ISSUE THREAD

**Issue by snowman11784** [DataDog/ansible-datadog#651]
I am trying to install the Datadog agent with APM singlestep on our fleet of RHEL machines, through the use of the Ansible "datadog.dd.agent" role within an "air-gapped" environment. We encountered a major roadblock when the job failed to pull the latest version of the "installer-package" image from an internal container registry.

<samp>TASK [datadog.dd.agent : Bootstrap the installer]</samp>
```json
{
  "error": "failed to bootstrap the installer: failed to download installer: failed to download installer package: could not download package: could not download image from any registry: could not download image using install.datadoghq.com/installer-package:latest: GET _https://<redacted regsitry URL>/v2/installer-package/manifests/latest:_ MANIFEST_UNKNOWN: manifest unknown; [map[Name:installer-package] map[Tag:latest]]",
  "code":0
}  
```
Our internal container registry does not use the "latest" tag and only contains "versioned" tags (e.g. installer-package:4.63).

<details><summary>datadog.dd.agent role default vars</summary>

  ```yaml
  
    datadog_apm_instrumentation_enabled: "host"
    datadog_apm_instrumentation_libraries: ["java:1", "python:2"]
    datadog_yum_repo_config_enabled: true
    datadog_remote_updates: false
    datadog_yum_repo: "<redacted>"
    datadog_yum_gpgkey_current: "{{ datadog_gpgkey_urlpath.stdout }}"
    datadog_yum_gpgkey_e09422b3: "{{ datadog_yum_gpgkey_current }}"
    datadog_yum_gpgkey_e09422b3_sha256sum: "{{ datadog_gpgkey_sha256checksum.stat.checksum }}"
    datadog_yum_gpgkey_20200908: "{{ datadog_yum_gpgkey_current }}"
    datadog_yum_gpgkey_20200908_sha256sum: "{{ datadog_gpgkey_sha256checksum.stat.checksum }}"
    datadog_yum_gpgkey_20280418: "{{ datadog_yum_gpgkey_current }}"
    datadog_yum_gpgkey_20280418_sha256sum: "{{ datadog_gpgkey_sha256checksum.stat.checksum }}"
    datadog_installer_registry: "<redacted registry URL>"
    datadog_agent_version: '7.64.3'
  ```
</details>

At this time, the Ansible [datadog.dd.agent](https://github.com/DataDog/ansible-datadog) role does not provide a versioned tag to the container images from the container registry source.

After digging through both the GitHub [ansible-datadog](https://github.com/DataDog/ansible-datadog) and [datadog-agent](https://github.com/DataDog/datadog-agent) repositories, I was able to locate the references to the default tag version "latest" of the container images within the source code for the "Bootstrap" Go package for "nix" machines.

<details><summary>bootstrap Go package snippet for Nix machines</summary>

  ```go

    package bootstrap
    ...
    // extractInstallerFromOCI downloads the installer binary from the agent package in the registry and returns an installer executor
    func downloadInstaller(ctx context.Context, env *env.Env, url string, tmpDir string) (*exec.InstallerExec, error) {
	  downloader := oci.NewDownloader(env, env.HTTPClient())
	  downloadedPackage, err := downloader.Download(ctx, url)
	  if err != nil {
	  	  return nil, fmt.Errorf("failed to download installer package: %w", err)
	  }
	  if downloadedPackage.Name != AgentPackage {
		  return getLocalInstaller(env)
	  }
        
	  installerBinPath := filepath.Join(tmpDir, "installer")
	  err = downloadedPackage.ExtractLayers(oci.DatadogPackageInstallerLayerMediaType, installerBinPath) // Returns nil if the layer doesn't exist
	  if err != nil {
		  return nil, fmt.Errorf("failed to extract layers: %w", err)
	  }
	  if _, err := os.Stat(installerBinPath); err != nil {
	          return nil, err
	  }
	  return exec.NewInstallerExec(env, installerBinPath), nil
    }
    
    func getInstallerOCI(_ context.Context, env *env.Env) (string, error) {
	  version := "latest"
	  if env.DefaultPackagesVersionOverride[InstallerPackage] != "" {
	   	  version = env.DefaultPackagesVersionOverride[InstallerPackage]
	  }
	  return oci.PackageURL(env, InstallerPackage, version), nil
    }
  ```
</details>

There is an environment variable named **DD_INSTALLER_DEFAULT_PKG_VERSION_DATADOG_INSTALLER**, which must get renamed or truncated to **DD_INSTALLER_DEFAULT_PKG_VERSION** - see <a href="https://github.com/DataDog/datadog-agent/blob/95010b0dc1c78d49538abcf5a355aa518cad8ebc/pkg/fleet/installer/env/env.go#L24-L37">datadog-agent installer environment variables</a>

I would like to see a feature request to override and set the **DD_INSTALLER_DEFAULT_PKG_VERSION_DATADOG_INSTALLER** environment variable during the ansible-datadog "[Bootstrap the installer](https://github.com/DataDog/ansible-datadog/blob/d2c880c73c3dbe4291a11020b6f99fc61d0ea58d/tasks/installer-setup.yml#L33-L50)" task as an environment variable. 

This feature would allow for more flexibility mainly within Air-Gapped environments.
