### ISSUE TITLE
Agent Install fails with No such file or directory: b''datadog-installer''' when datadog_remote_updates: true

### ISSUE THREAD

**Issue by josiahwitheford** [DataDog/ansible-datadog#663]
**Ansible script**
```
- name: Install Datadog Agent
  hosts: all
  become: true
  gather_facts: true
  collections:
    - datadog.dd
  tasks:
    - name: Import the Datadog Agent role from the Datadog collection
      import_role:
        name: datadog.dd.agent
  vars:
    datadog_remote_updates: true
    datadog_installer_version: "7.62" 
    datadog_disable_default_checks: true
    datadog_api_key: "{{ lookup('ansible.builtin.env', 'DATADOG_API_KEY', default=undef() ) }}"
    datadog_config:
      apm_config:
        enabled: true
      logs_enabled: true
      process_config:
        enabled: true
    network_config:
      enabled: true
    system_probe_config:
      sysprobe_socket: /opt/datadog-agent/run/sysprobe.sock
    system_probe_other_config:
      traceroute:
        enabled: true
    service_monitoring_config:
      enabled: true
```

**Host Information:**
```
OS: Linux Ubuntu 22.04.4 LTS (Jammy Jellyfish)
```

**Installer version:** 7.63.0-installer-0.12.14

We used ansible to deploy the agent initially to our linux servers. After it was installed we realized that **remote_updates** was disabled. This was because we set the remote_updates flag inside the datadog_config section of the vars block. Updating the `/etc/datadog/datadog.conf` file to include **remote_updates: true** did not actually enable the functionality. We could see the config had updated from the datadog dashboard, however the host never became available for deploying a new config.

We have followed the uninstall guide for the datadog agent, running the following commands.

```bash
apt-get remove datadog-agent -y
apt get remove datadog-agent --purge
```

Have also run the following
```bash
apt-get remove datadog-installer -y
apt-get remove datadog-installer --purge

apt-get remove datadog-signing-keys -y
apt-get remove datadog-signing-keys --purge
```

The rerunning ansible with the correct **datadog_remote_updates: true** variable set results in the following error.

```TASK [datadog.dd.agent : Install Datadog installer (apt)] **********************
The following packages were automatically installed and are no longer required:
  geoclue-2.0 iio-sensor-proxy libavahi-glib1 libdouble-conversion3 libmd4c0
  libnotify4 libpcre2-16-0 libqt5core5a libqt5dbus5 libqt5gui5 libqt5network5
  libqt5positioning5 libqt5printsupport5 libqt5qml5 libqt5qmlmodels5
  libqt5quick5 libqt5sensors5 libqt5svg5 libqt5webchannel5 libqt5webkit5
  libqt5widgets5 libxcb-icccm4 libxcb-image0 libxcb-keysyms1
  libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xkb1
  libxkbcommon-x11-0 qt5-gtk-platformtheme qttranslations5-l10n
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  datadog-signing-keys
The following NEW packages will be installed:
  datadog-installer datadog-signing-keys
0 upgraded, 2 newly installed, 0 to remove and 89 not upgraded.
changed: [hostname]
TASK [datadog.dd.agent : Build Datadog installer environment variables] ********
ok: [hostname]
TASK [datadog.dd.agent : Bootstrap the installer] ******************************
changed: [hostname]
TASK [datadog.dd.agent : Check if installer owns datadog-agent package] ********
fatal: [hostname]: FAILED! => changed=true 
  cmd: datadog-installer is-installed datadog-agent
  failed_when_result: true
  msg: '[Errno 2] No such file or directory: b''datadog-installer'''
  rc: 2
  stderr: ''
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
PLAY RECAP *********************************************************************
```

- From what I can see, enabling the **datadog_remote_updates** flag installs the `datadog-installer` package instead of just the `datadog-agent`. There seems to be something kept on the machine from the previous install that is preventing the installer from running properly.

It works fine on a new host, however we can't be rebuilding these hosts. We would like to get the agent installed and remotely configurable.

Any ideas would be greatly appreciated. We have raised a support case as well, but just posting this here in case others see the same behaviour.

Cheers
