### ISSUE TITLE
Invalid yaml from `datadog_checks`

### ISSUE THREAD

**Issue by grinnery** [DataDog/ansible-datadog#72]
Trying to generate docker daemon config with: 
```
...blah-blah-blah...
  vars:                                       
    datadog_checks:                           
      docker:                                 
        init_config:                          
        instances:                            
          - url: "unix://var/run/docker.sock" 
```

and getting `docker.yaml`, which does not work:
```
init_config: null
instances:
-   url: unix://var/run/docker.sock
```

Likely related to [this issue](https://github.com/ansible/ansible/issues/16707) with jinja's `to_nice_yaml`

**Comment by dkeightley** [comment]
I'm experiencing a similar issue, the ordering of `to_nice_yaml` isn't respecting the input and yaml standards it seems.

I have the following for the playbook datadog_checks variable:

```
datadog_checks:
  elastic:
    init_config:
    instances:
      - url: http://localhost:9200
        pshard_stats: true
```

Trying to generate an elastic.yml config like:

```
init_config: null
instances:
  - url: http://localhost:9200
    pshard_stats: true
```

I'm getting:

```
init_config: null
instances:
-   pshard_stats: true
    url: http://localhost:9200
```

Working on an alternative, anyone have any suggestions for a more reliable way to pump yaml?

**Comment by tekkno89** [comment]
also having the same issue
ansible var:
```yaml
datadog_checks:
  process:
    init_config:
    instances:
      - name: airflow_worker
        search_string: ['celery']
```

config result:
```yaml
init_config: null
instances:
-   name: airflow_worker
    search_string:
    - celery
```

**Comment by olivielpeau** [comment]
Hi everyone!

All the examples that are given on this issue do not show any discrepancy between the ansible vars and the config results. In each example, the vars and the config result are semantically identical YAMLs.

For example if you have the following var:

```yml
instances:
  - url: http://localhost:9200
    pshard_stats: true
```

and you get the following result in your config:

```yml
instances:
- pshard_stats: true
  url: http://localhost:9200
```

the 2 are semantically the same YAML maps, and could be represented in JSON with:

```json
{
  "instances": [
    {
      "pshard_stats": true, 
      "url": "http://localhost:9200"
    }
  ]
}
```

Also, please note the keys of YAML maps are unordered (similarly to JSON).

YAML can be a bit hard to grasp, I'd recommend using a YAML-to-JSON parser to more easily compare different YAML files (http://yaml-online-parser.appspot.com/ for example).

Going to go ahead and close this issue. Feel free to comment here if you have questions!
