### ISSUE TITLE
Check datadog agent `info` for warnings & errors, failing the play if any are found

### ISSUE THREAD

**Issue by bgerstle** [DataDog/ansible-datadog#73]
As a user, I expect an attempt to configure the datadog-agent improperly would result in a play failure. Instead, it fails silently and I don't realize monitoring is broken until after the fact.

It seems this could be accomplished with something along these lines:

``` yaml
- name: Get datadog-agent status
  command: /etc/init.d/datadog-agent info
  register: agent_info

- fail: "Something seems wrong with your configuration, please check the docs"
  when: 'WARNING' in agent_info or 'ERROR' in agent-info
```
