### ISSUE TITLE
Ansible dry-run failed on pkg-redhat.yml

### ISSUE THREAD

**Issue by chaosoldier** [DataDog/ansible-datadog#75]
"Import new RPM key" task was failed when I run "tasks/pkg-redhat.yml" with dry-run mode. Because dry-run mode had not made the fie "/tmp/DATADOG_RPM_KEY_E09422B3.public". 
And, sometimes any files in /tmp directory may be deleted by setting. 
So, I add  "always_run: yes" to get_url task . (in 2.X must change to check_mode: no) 

```
- name: Download new RPM key
  get_url:
    url: "http://yum.datadoghq.com/DATADOG_RPM_KEY_E09422B3.public"
    dest: /tmp/DATADOG_RPM_KEY_E09422B3.public
    sha256sum: 694a2ffecff85326cc08e5f1a619937999a5913171e42f166e13ec802c812085

- name: Import new RPM key
  rpm_key: key=/tmp/DATADOG_RPM_KEY_E09422B3.public state=present
```
