### ISSUE TITLE
ansible fails to install datadog on debian stretch

### ISSUE THREAD

**Issue by lvnilesh** [DataDog/ansible-datadog#83]
```
TASK [Datadog.datadog : Install ubuntu apt-key server] *************************************************
fatal: [manager0]: FAILED! => 
{
  "changed": false,
  "cmd": "/usr/bin/apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv A2923DFF56EDA6E76E55E492D3A80E30382E94DE",
  "failed": true,
  "msg": "Error fetching key A2923DFF56EDA6E76E55E492D3A80E30382E94DE from keyserver: hkp://keyserver.ubuntu.com:80",
  "rc": 2,
  "stderr": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory\ngpg: connecting dirmngr at '/tmp/apt-key-gpghome.YVCEPPnGZk/S.dirmngr' failed: No such file or directory\ngpg: keyserver receive failed: No dirmngr\n",
  "stderr_lines": [
    "Warning: apt-key output should not be parsed (stdout is not a terminal)",
    "gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory",
    "gpg: connecting dirmngr at '/tmp/apt-key-gpghome.YVCEPPnGZk/S.dirmngr' failed: No such file or directory",
    "gpg: keyserver receive failed: No dirmngr"
  ],
  "stdout": "Executing: /tmp/apt-key-gpghome.YVCEPPnGZk/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv A2923DFF56EDA6E76E55E492D3A80E30382E94DE\n",
  "stdout_lines": [
    "Executing: /tmp/apt-key-gpghome.YVCEPPnGZk/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv A2923DFF56EDA6E76E55E492D3A80E30382E94DE"
  ]
}
```

**Comment by olivielpeau** [comment]
Thanks @lvnilesh for reporting this!

I think this issue should be reported upstream to [ansible/ansible](https://github.com/ansible/ansible). In our experience the root cause is that Debian Stretch requires the `dirmngr` package to be installed in order to use the `apt-key` command, and it seems like ansible doesn't check for the existence of that package.

Can you try adding the following task at the beginning of your playbook:

```yaml
- name: Install "dirmngr" package
  apt:
    name: dirmngr
    state: present
```

and see if that fixes the issue? Thanks!

For reference, related to: https://github.com/DataDog/dd-agent-omnibus/pull/188

**Comment by lvnilesh** [comment]
I will try this and update you. In the meanwhile, appreciate if you can please update the datadog help doc. Also including some datadog ansible usage examples would be great. 

Thanks.

**Comment by lvnilesh** [comment]
This sequence failed in first attempt because the role execution started before apt installed `dirmngr` so I manually worked around. 

What would be the right way to structure a datadog playbook given this debian stretch constraint? 

```
---
- hosts: all
  tasks:
    - name: Debian Stretch requires dirmngr package to be installed in order to use the apt-key
      apt:
        name: dirmngr
        state: present

  roles:
    - { role: Datadog.datadog, become: yes, datadog_api_key: "asdasdasd" } # On Ansible < 1.9, use "sudo: yes" instead of "become: yes"
```

**Comment by lvnilesh** [comment]
https://app.datadoghq.com/account/settings#agent/ansible

This page could use better instructions.

**Comment by olivielpeau** [comment]
@lvnilesh to make sure the task is executed before the role, you can define it in the `pre_tasks` of your playbook, i.e.:

```
---
- hosts: all
  pre_tasks:
    - name: Debian Stretch requires dirmngr package to be installed in order to use the apt-key
      apt:
        name: dirmngr
        state: present
      become: yes

  roles:
    - { role: Datadog.datadog, become: yes, datadog_api_key: "asdasdasd" }
```

This is worth documenting in the `README` of the present repo but I'd like to avoid having too much information on the `app.datadoghq.com` page. Feel free to open a PR to update the readme, otherwise I can take care of it, thanks!

**Comment by lvnilesh** [comment]
`become: yes` is not valid for apt module. I think it needs to be specified at host level.
```
{
  "changed": false,
  "failed": true,
  "msg": "Unsupported parameters for (apt) module: become Supported parameters include: allow_unauthenticated,autoclean,autoremove,cache_valid_time,deb,default_release,dpkg_options,force,force_apt_get,install_recommends,only_upgrade,package,purge,state,update_cache,upgrade"
}
```

**Comment by lvnilesh** [comment]
Also, `sudo usermod -aG docker dd-agent` seems necessary otherwise dd-agent throws permissions error. 

So I play like this. 
```
---
- hosts: all
  become: true
  pre_tasks:
    - name: Debian Stretch requires dirmngr package to be installed in order to use the apt-key
      apt:
        name: dirmngr
        state: present
    - name: sudo usermod -aG docker dd-agent
      command: sudo usermod -aG docker dd-agent
```
