### ISSUE TITLE
Can't set thresholds on process checks

### ISSUE THREAD

**Issue by szponek** [DataDog/ansible-datadog#96]
Hi,

I'm trying to set thresholds on process checks but the following yaml doesn't result in output datadog-agent can use (regardless of any quoting I tried to introduce):
```
process:
    init_config:
      pid_cache_duration: 10
    instances:
      - name: sshd
        collect_children: true
        pid_file: /run/sshd.pid
        thresholds:
          critical: [1,150]
```
'to_nice_yaml' filter used in from checks.yaml.j2 interprets [1,150] as a list and results in the following output:
```
init_config:
    pid_cache_duration: 10
instances:
-   collect_children: true
    name: sshd
    pid_file: /run/sshd.pid
    thresholds:
    - 1
    - 150
```
What I expect to see is this:
```
init_config:
    pid_cache_duration: 10
instances:
-   collect_children: true
    name: sshd
    pid_file: /run/sshd.pid
    thresholds: [1,150]
```
just as described at https://github.com/DataDog/integrations-core/blob/master/process/conf.yaml.example#L46

**Comment by hush-hush** [comment]
Hi @szponek,

In Yaml both syntax: 
```
thresholds: [1,150]
```
and:
```
thresholds:
- 1
- 150
```

are valid and produce the same data once loaded (see ansible doc: http://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html#yaml-basics).

Closing this since it does not seem like an issue, but feel free to reopen if needed.

**Comment by szponek** [comment]
Hi @hush-hush 

I agree that this syntax is valid in ansible variable files. The issue is with datadog agent parsing it's configuration files created from checks.yaml.j2 template.

While they also have valid yaml syntax, datadog agent doesn't accept when the thresholds are defined as anything different than a literal string i.e '[1,5]'

While it's an issue with datadog agent rather then this ansible module, I was hoping there might be a workaround for that.

**Comment by borgoat** [comment]
I'm seeing the same but with `search_string`:

in my Ansible vars:
```yaml
datadog_checks:
  process:
    init_config:
    instances:
      - name: ssh
        search_string: ['ssh', 'sshd']
```

in `process.d/conf.yaml`:
```yaml
init_config: null
instances:
-   name: ssh
    search_string:
    - ssh
    - sshd
```

Replacing the last three lines with the following fixes the issue...
```
search_string: [ 'ssh', 'sshd' ]
```
